Repository AVSLab/basilisk, pull requests merged in 2023-12, with the labels that each got.

#520 Feature/494 sep point scenario
  docs/source/Support/bskReleaseNotes.rst
  examples/_default.rst
  examples/scenarioSepMomentumManagement.py
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/thrustCMEstimation.rst
  src/tests/test_scenarioSepMomentumManagement.py
Labels: enhancement

#522 remove two unused method parameters from documentation
  src/fswAlgorithms/smallBodyNavigation/smallBodyNavUKF/smallBodyNavUKF.cpp
Labels: bug, documentation

#526 Correct windows debug build flags
  docs/source/Install/installOnWindows.rst
  docs/source/Support/User/createHtmlDocumentation.rst
  docs/source/_images/static/windows-installer-python-advanced-options-installer-menu.png
  docs/source/_images/static/windows-installer-python-optional-features-installer-menu.png
  docs/source/bskPkgOptions.txt
  src/CMakeLists.txt
Labels: build

#513 Feature/accumulated dv inertial frame
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/msgPayloadDefC/SCStatesMsgPayload.h
  src/simulation/dynamics/spacecraft/_UnitTest/test_spacecraft.py
  src/simulation/dynamics/spacecraft/spacecraft.cpp
  src/simulation/dynamics/spacecraft/spacecraft.h
Labels: enhancement

#537 input connector is a single msg, not vector of msgs
  docs/source/Vizard/vizardAdvanced/vizardSettings.rst
Labels: bug, documentation

#514 Bug/spinning bodies initialization
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/spinningBodyOneDOFStateEffector.cpp
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/spinningBodyOneDOFStateEffector.h
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/spinningBodyTwoDOFStateEffector.cpp
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/spinningBodyTwoDOFStateEffector.h
Labels: bug

#543 improve Windows Install notes
  docs/source/Install/installOnWindows.rst
Labels: documentation

#539 Walker Delta Constellation Scenario
  docs/source/Support/bskReleaseNotes.rst
  docs/source/_images/static/scenarioSatelliteConstellationVizard.jpg
  examples/_default.rst
  examples/scenarioSatelliteConstellation.py
  src/tests/test_scenarioSatelliteConstellation.py
Labels: enhancement

#534 Feature/fix first start
  docs/source/Learn/bskPrinciples/bskPrinciples-1.rst
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioSmallBodyNav.py
  src/architecture/system_model/sys_model_task.cpp
  src/architecture/system_model/sys_model_task.h
  src/utilities/SimulationBaseClass.py
  src/utilities/simulationArchTypes.py
Labels: documentation

#545 Terminate at time of terminal events instead of a step later
  docs/source/Support/bskReleaseNotes.rst
  src/utilities/SimulationBaseClass.py
Labels: bug

#546 BSK version 2.2.1 tagged release
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskVersion.txt
Labels: documentation

#547 Setup next Basilisk beta cycle
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskVersion.txt
Labels: documentation
