Repository AVSLab/basilisk, pull requests merged in 2023-05, with the labels that each got.

#308 Feature/bsk 307 c msg read
  docs/source/Learn/bskPrinciples/bskPrinciples-7.rst
  docs/source/codeSamples/bsk-7.py
  src/architecture/messaging/_UnitTest/test_RecordInputMessages.py
  src/architecture/messaging/msgAutoSource/cMsgCInterfacePy.i.in
  src/architecture/messaging/msgAutoSource/msg_C.cpp.in
Labels: bug

#310 Custom Radius in Eclipse Module
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/environment/eclipse/_UnitTest/test_eclipse.py
  src/simulation/environment/eclipse/eclipse.cpp
  src/simulation/environment/eclipse/eclipse.h
  src/simulation/environment/eclipse/eclipse.rst
Labels: enhancement

#313 Feature/312 eigen swig int support
  docs/source/Support/bskReleaseNotes.rst
  examples/OpNavScenarios/scenariosOpNav/CNN_ImageGen/scenario_CNNImages.py
  examples/OpNavScenarios/scenariosOpNav/OpNavMC/scenario_LimbAttOD.py
  examples/OpNavScenarios/scenariosOpNav/OpNavMC/scenario_OpNavAttODMC.py
  examples/OpNavScenarios/scenariosOpNav/scenario_CNNAttOD.py
  examples/OpNavScenarios/scenariosOpNav/scenario_OpNavAttOD.py
  examples/OpNavScenarios/scenariosOpNav/scenario_OpNavAttODLimb.py
  examples/OpNavScenarios/scenariosOpNav/scenario_OpNavHeading.py
  examples/OpNavScenarios/scenariosOpNav/scenario_OpNavOD.py
  examples/OpNavScenarios/scenariosOpNav/scenario_OpNavODLimb.py
  examples/OpNavScenarios/scenariosOpNav/scenario_OpNavPoint.py
  examples/OpNavScenarios/scenariosOpNav/scenario_OpNavPointLimb.py
  examples/OpNavScenarios/scenariosOpNav/scenario_faultDetOpNav.py
  examples/scenarioAlbedo.py
  examples/scenarioAsteroidArrival.py
  examples/scenarioGroundMapping.py
  examples/scenarioJupiterArrival.py
  examples/scenarioOrbitManeuver.py
  examples/scenarioPatchedConics.py
  examples/scenarioRendezVous.py
  examples/scenarioSmallBodyNav.py
  examples/scenarioSmallBodyNavUKF.py
  examples/scenarioSpacecraftLocation.py
  src/architecture/_GeneralModuleFiles/swig_eigen.i
  src/architecture/utilitiesSelfCheck/_UnitTest/test_swigEigen.py
  src/architecture/utilitiesSelfCheck/swigEigenCheck.i
  src/fswAlgorithms/smallBodyNavigation/smallBodyNavEKF/_UnitTest/test_smallBodyNavEKF.py
  src/fswAlgorithms/smallBodyNavigation/smallBodyNavUKF/_UnitTest/test_smallBodyNavUKF.py
  src/simulation/environment/groundMapping/_UnitTest/test_groundMapping.py
  src/simulation/environment/spacecraftLocation/_UnitTest/test_unitSpacecraftLocation.py
  src/simulation/environment/spacecraftLocation/spacecraftLocation.rst
  src/utilities/unitTestSupport.py
Labels: enhancement

#318 RST documentation throwing a warning
  src/simulation/dynamics/_GeneralModuleFiles/dynamicObject.cpp
  src/simulation/dynamics/_GeneralModuleFiles/dynamicObject.h
Labels: bug

#192 Feature/bsk 68 facet srp dynamic effector
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/_GeneralModuleFiles/dynamicEffector.h
  src/simulation/dynamics/facetDragEffector/facetDragDynamicEffector.h
  src/simulation/dynamics/facetSRPDynamicEffector/_UnitTest/test_unitFacetSRPDynamicEffector.py
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.cpp
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.h
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.i
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.rst
Labels: enhancement

#127 Prototype/bsk 126 prescribed rot2 dof
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/effectorInterfaces/prescribedRot2DOF/_UnitTest/test_prescribedRot2DOF.py
  src/fswAlgorithms/effectorInterfaces/prescribedRot2DOF/prescribedRot2DOF.c
  src/fswAlgorithms/effectorInterfaces/prescribedRot2DOF/prescribedRot2DOF.h
  src/fswAlgorithms/effectorInterfaces/prescribedRot2DOF/prescribedRot2DOF.i
  src/fswAlgorithms/effectorInterfaces/prescribedRot2DOF/prescribedRot2DOF.rst
Labels: enhancement

#344 Feature/doc fix
  examples/MultiSatBskSim/scenariosMultiSat/scenario_BasicOrbitMultiSat.py
  examples/MultiSatBskSim/scenariosMultiSat/scenario_BasicOrbitMultiSat_MT.py
  examples/scenarioAlbedo.py
  examples/scenarioDataToViz.py
  examples/scenarioDragRendezvous.py
  examples/scenarioFormationMeanOEFeedback.py
  examples/scenarioGroundMapping.py
  src/fswAlgorithms/effectorInterfaces/dipoleMapping/dipoleMapping.rst
  src/simulation/dynamics/MtbEffector/MtbEffector.rst
Labels: documentation

#336 Fix incorrect conversion macro in accuracyNanos
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/simSynch/simSynch.cpp
Labels: bug

#323 Feature/320 deprecation system
  docs/source/Support/Developer.rst
  docs/source/Support/Developer/deprecatingCode.rst
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioAttitudePointingPyDEPRECATED.py
  src/architecture/_GeneralModuleFiles/swig_deprecated.i
  src/architecture/utilitiesSelfCheck/_UnitTest/test_swigDeprecated.py
  src/architecture/utilitiesSelfCheck/swigDeprecatedCheck.i
  src/pytest.ini
  src/tests/test_deprecated.py
  src/tests/test_scenarioAttitudePointingPyDEPRECATED.py
  src/utilities/SimulationBaseClass.py
  src/utilities/deprecated.py
Labels: enhancement

#348 the code sample bsk-3 script was not running when called directly
  docs/source/codeSamples/bsk-3.py
Labels: bug

#349 Update tests to not use deprecated Python modules
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_UnitTest/test_thruster_dynamics_attached_body.py
  src/simulation/dynamics/Thrusters/thrusterStateEffector/_UnitTest/test_ThrusterStateEffectorUnit.py
Labels: enhancement

#322 Refactor/bsk 321 denton flux module
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/msgPayloadDefC/PlasmaFluxMsgPayload.h
  src/simulation/environment/dentonFluxModel/_UnitTest/test_dentonFluxModel.py
  src/simulation/environment/dentonFluxModel/dentonFluxModel.cpp
  src/simulation/environment/dentonFluxModel/dentonFluxModel.h
Labels: refactor

#319 Eclipse skips over potentially occluding bodies
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/environment/eclipse/_UnitTest/test_eclipse.py
  src/simulation/environment/eclipse/eclipse.cpp
Labels: bug

#356 Fix C/C++ test invocation in windows CI job
  .github/workflows/pull-request.yml
Labels: ci

#352 Feature/fix msis
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/environment/MsisAtmosphere/msisAtmosphere.cpp
Labels: bug

#358 Feature/fix compiler warnings
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/thrusterDynamicEffector.cpp
  src/simulation/dynamics/Thrusters/thrusterStateEffector/thrusterStateEffector.cpp
  src/simulation/dynamics/VSCMGs/vscmgStateEffector.cpp
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.h
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.h
  src/simulation/dynamics/reactionWheels/reactionWheelStateEffector.cpp
  src/simulation/environment/albedo/albedo.cpp
  src/simulation/environment/magneticFieldWMM/GeomagnetismLibrary.c
  src/simulation/onboardDataHandling/spaceToGroundTransmitter/spaceToGroundTransmitter.cpp
  src/simulation/power/_GeneralModuleFiles/powerNodeBase.cpp
  src/simulation/vizard/dataFileToViz/dataFileToViz.cpp
Labels: bug, build
