Repository AVSLab/basilisk, pull requests merged in 2023-08, with the labels that each got.

#403 Feature/2 dof scenario
  docs/source/Support/bskReleaseNotes.rst
  examples/_default.rst
  examples/scenarioSpinningBodiesTwoDOF.py
  src/tests/test_scenarioSpinningBodiesTwoDOF.py
Labels: enhancement

#405 thrusterStateEffector nameOfKappaState bug
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/Thrusters/thrusterStateEffector/thrusterStateEffector.cpp
  src/simulation/dynamics/_GeneralModuleFiles/dynParamManager.cpp
Labels: bug

#414 Feature/update conan dependencies
  conanfile.py
  docs/source/Support/bskKnownIssues.rst
Labels: bug

#412 Magnetometer fix noise initialization
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/sensors/magnetometer/magnetometer.cpp
Labels: bug

#419 Refactor/418 mrp feedback control law flag
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/attControl/mrpFeedback/_UnitTest/test_mrpFeedback.py
  src/fswAlgorithms/attControl/mrpFeedback/mrpFeedback.c
  src/fswAlgorithms/attControl/mrpFeedback/mrpFeedback.h
  src/fswAlgorithms/attControl/mrpFeedback/mrpFeedback.rst
Labels: enhancement, refactor
