Repository AVSLab/basilisk, pull requests merged in 2023-03, with the labels that each got.

#177 Feature/bsk 71 two axis rotating rigid bodies
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/_UnitTest/test_spinningBodyTwoDOFStateEffector.py
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/spinningBodyTwoDOFStateEffector.cpp
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/spinningBodyTwoDOFStateEffector.h
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/spinningBodyTwoDOFStateEffector.i
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/spinningBodyTwoDOFStateEffector.rst
Labels: enhancement

#230 Fixed documentation to reference the published JSR paper
  src/fswAlgorithms/attGuidance/constrainedAttitudeManeuver/constrainedAttitudeManeuver.rst
Labels: documentation

#167 Feature/bsk 144 one axis solar array point
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/msgPayloadDefC/InertialHeadingMsgPayload.h
  src/architecture/utilities/linearAlgebra.c
  src/architecture/utilities/linearAlgebra.h
  src/architecture/utilitiesSelfCheck/avsLibrarySelfCheck.c
  src/fswAlgorithms/attGuidance/oneAxisSolarArrayPoint/_UnitTest/test_oneAxisSolarArrayPoint.py
  src/fswAlgorithms/attGuidance/oneAxisSolarArrayPoint/oneAxisSolarArrayPoint.c
  src/fswAlgorithms/attGuidance/oneAxisSolarArrayPoint/oneAxisSolarArrayPoint.h
  src/fswAlgorithms/attGuidance/oneAxisSolarArrayPoint/oneAxisSolarArrayPoint.i
  src/fswAlgorithms/attGuidance/oneAxisSolarArrayPoint/oneAxisSolarArrayPoint.rst
Labels: enhancement

#219 Feature/bsk 141 add maximum reaction wheel power
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/msgPayloadDefC/RWConfigLogMsgPayload.h
  src/architecture/msgPayloadDefCpp/RWConfigMsgPayload.h
  src/simulation/dynamics/reactionWheels/_Documentation/Basilisk-REACTIONWHEELSTATEEFFECTOR-20170816.pdf
  src/simulation/dynamics/reactionWheels/_Documentation/Basilisk-REACTIONWHEELSTATEEFFECTOR-20170816.tex
  src/simulation/dynamics/reactionWheels/_Documentation/secModelFunctions.tex
  src/simulation/dynamics/reactionWheels/_Documentation/secTest.tex
  src/simulation/dynamics/reactionWheels/_Documentation/secUserGuide.tex
  src/simulation/dynamics/reactionWheels/_UnitTest/test_reactionWheelStateEffector_ConfigureRWRequests.py
  src/simulation/dynamics/reactionWheels/_UnitTest/test_reactionWheelStateEffector_RWUpdate.py
  src/simulation/dynamics/reactionWheels/reactionWheelStateEffector.cpp
  src/utilities/simIncludeRW.py
Labels: enhancement

#238 Refactor/bsk 237 documentation refactor
  src/fswAlgorithms/attGuidance/oneAxisSolarArrayPoint/_UnitTest/test_oneAxisSolarArrayPoint.py
  src/fswAlgorithms/attGuidance/oneAxisSolarArrayPoint/oneAxisSolarArrayPoint.c
  src/fswAlgorithms/attGuidance/oneAxisSolarArrayPoint/oneAxisSolarArrayPoint.h
  src/fswAlgorithms/attGuidance/oneAxisSolarArrayPoint/oneAxisSolarArrayPoint.rst
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/solarArrayReference.c
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/solarArrayReference.h
Labels: bug

#204 Feature/bsk 180 thruster platform reference
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/_UnitTest/test_thrusterPlatformReference.py
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/thrusterPlatformReference.c
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/thrusterPlatformReference.h
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/thrusterPlatformReference.i
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/thrusterPlatformReference.rst
Labels: enhancement

#242 Fixed dead link
  docs/source/Support/User/createHtmlDocumentation.rst
Labels: documentation

#256 Feature/fix viz interface com
  conanfile.py
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
Labels: bug

#223 Provide support for Vizard 2.1.4
  docs/source/Support/bskReleaseNotes.rst
  docs/source/Vizard/Vizard.rst
  docs/source/Vizard/VizardReleaseNotes.rst
  docs/source/Vizard/vizardAdvanced/vizardSettings.rst
  examples/scenarioDeployingPanel.py
  examples/scenarioHelioTransSpice.py
  src/architecture/msgPayloadDefC/ColorMsgPayload.h
  src/simulation/dynamics/_GeneralModuleFiles/stateEffector.h
  src/simulation/dynamics/dualHingedRigidBodies/_UnitTest/test_dualhingedRigidBodyStateEffector.py
  src/simulation/dynamics/dualHingedRigidBodies/dualHingedRigidBodyStateEffector.rst
  src/simulation/vizard/_GeneralModuleFiles/vizStructures.h
  src/simulation/vizard/vizInterface/vizInterface.cpp
  src/utilities/vizProtobuffer/vizMessage.proto
  src/utilities/vizSupport.py
Labels: enhancement

#234 Feature/bsk 2 1 7
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskVersion.txt
Labels: documentation

#235 Feature/bsk 2 2 0 beta
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskVersion.txt
Labels: documentation

#224 Feature/bsk 195 integration dyn objects
  docs/source/Learn/bskPrinciples.rst
  docs/source/Learn/bskPrinciples/bskPrinciples-9.rst
  docs/source/Learn/makingModules.rst
  docs/source/Learn/makingModules/advancedTopics.rst
  docs/source/Learn/makingModules/advancedTopics/creatingDynObject.rst
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioFormationBasic.py
  src/simulation/dynamics/Integrators/svIntegratorEuler.cpp
  src/simulation/dynamics/Integrators/svIntegratorRK2.cpp
  src/simulation/dynamics/Integrators/svIntegratorRKF45.cpp
  src/simulation/dynamics/Integrators/svIntegratorRKF78.cpp
  src/simulation/dynamics/_GeneralModuleFiles/dynamicObject.cpp
  src/simulation/dynamics/_GeneralModuleFiles/dynamicObject.h
  src/simulation/dynamics/_GeneralModuleFiles/stateVecIntegrator.cpp
  src/simulation/dynamics/_GeneralModuleFiles/stateVecIntegrator.h
  src/simulation/dynamics/_GeneralModuleFiles/svIntegratorRK4.cpp
  src/simulation/dynamics/spacecraft/spacecraft.cpp
  src/simulation/dynamics/spacecraft/spacecraft.h
  src/simulation/dynamics/spacecraftSystem/spacecraftSystem.cpp
  src/simulation/dynamics/spacecraftSystem/spacecraftSystem.h
Labels: enhancement

#271 fix RST documentation warning
  examples/_default.rst
Labels: bug, documentation
