Repository AVSLab/basilisk, pull requests merged in 2023-02, with the labels that each got.

#169 Refactor/bsk 165 sensor thermal edits
  src/simulation/thermal/sensorThermal/sensorThermal.cpp
  src/simulation/thermal/sensorThermal/sensorThermal.h
  src/simulation/thermal/sensorThermal/sensorThermal.rst
Labels: documentation, refactor

#168 Create tempMeasurement module to add noise and faults to temp readings
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/deviceInterface/tempMeasurement/_UnitTest/test_tempMeasurement.py
  src/simulation/deviceInterface/tempMeasurement/tempMeasurement.cpp
  src/simulation/deviceInterface/tempMeasurement/tempMeasurement.h
  src/simulation/deviceInterface/tempMeasurement/tempMeasurement.i
  src/simulation/deviceInterface/tempMeasurement/tempMeasurement.rst
Labels: enhancement

#174 BSK-173: Add terminal event flag and demonstrate use in scenario.
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioDragDeorbit.py
  src/tests/test_scenarioDragDeorbit.py
  src/utilities/SimulationBaseClass.py
Labels: enhancement

#114 Feature/bsk 113 prescribed motion
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/msgPayloadDefC/PrescribedMotionMsgPayload.h
  src/architecture/msgPayloadDefC/PrescribedTransMsgPayload.h
  src/fswAlgorithms/effectorInterfaces/prescribedRot1DOF/_UnitTest/test_prescribed1DOF.py
  src/fswAlgorithms/effectorInterfaces/prescribedRot1DOF/prescribedRot1DOF.c
  src/fswAlgorithms/effectorInterfaces/prescribedRot1DOF/prescribedRot1DOF.h
  src/fswAlgorithms/effectorInterfaces/prescribedRot1DOF/prescribedRot1DOF.i
  src/fswAlgorithms/effectorInterfaces/prescribedRot1DOF/prescribedRot1DOF.rst
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/_UnitTest/test_prescribedTrans.py
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/prescribedTrans.c
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/prescribedTrans.h
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/prescribedTrans.i
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/prescribedTrans.rst
  src/simulation/dynamics/prescribedMotion/_UnitTest/test_PrescribedMotionStateEffector.py
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.cpp
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.h
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.i
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.rst
Labels: enhancement

#133 Feature/bsk 84 solar array reference
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/_UnitTest/test_solarArrayReference.py
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/solarArrayReference.c
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/solarArrayReference.h
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/solarArrayReference.i
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/solarArrayReference.rst
Labels: enhancement

#175 Improve and Refactor spinningBodiesOneDOF
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/_UnitTest/test_spinningBodyOneDOFStateEffector.py
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/spinningBodyOneDOFStateEffector.cpp
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/spinningBodyOneDOFStateEffector.h
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/spinningBodyOneDOFStateEffector.i
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/spinningBodyOneDOFStateEffector.rst
Labels: enhancement, refactor

#215 Feature/doc updates
  docs/source/Support/User.rst
  docs/source/Support/User/FAQ.rst
  docs/source/Support/User/FAQmacOS.rst
  docs/source/_images/static/FAQmacOS1.png
  examples/scenarioIntegrators.py
  src/utilities/fswSetupRW.py
Labels: bug, documentation
