Repository AVSLab/basilisk, pull requests merged in 2023-10, with the labels that each got.

#444 Prescribed Spinning Bodies Message
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/_UnitTest/test_spinningBodyOneDOFStateEffector.py
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/spinningBodyOneDOFStateEffector.cpp
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/spinningBodyOneDOFStateEffector.h
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/spinningBodyOneDOFStateEffector.i
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/spinningBodyOneDOFStateEffector.rst
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/_UnitTest/test_spinningBodyTwoDOFStateEffector.py
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/spinningBodyTwoDOFStateEffector.cpp
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/spinningBodyTwoDOFStateEffector.h
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/spinningBodyTwoDOFStateEffector.rst
Labels: enhancement

#442 Add Hohmann transfer and attitude change integrated scenario script
  docs/source/Support/bskReleaseNotes.rst
  examples/_default.rst
  examples/scenarioHohmann.py
  src/tests/test_scenarioHohmann.py
Labels: enhancement

#438 Feature/doc warning fix
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/_GeneralModuleFiles/sys_model.h
  src/simulation/sensors/camera/camera.cpp
Labels: documentation

#452 Feature/bsk 451 sonoma support
  .github/workflows/pull-request.yml
  conanfile.py
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskPkgRequired.txt
Labels: build

#472 Fix Bug in SRP Dynamic Effector Module
  docs/source/Support/bskKnownIssues.rst
  src/simulation/dynamics/facetSRPDynamicEffector/_UnitTest/test_unitFacetSRPDynamicEffector.py
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.cpp
Labels: bug
