Repository AVSLab/basilisk, pull requests merged in 2023-11, with the labels that each got.

#476 Feature/bsk 462 rounding
  docs/source/Support/bskReleaseNotes.rst
  examples/BskSim/scenarios/scenario_AttModes.py
  src/utilities/macros.py
Labels: bug

#479 Bsk 474/fix drag effector
  docs/source/Support/bskKnownIssues.rst
  src/simulation/dynamics/facetDragEffector/_UnitTest/test_unitFacetDrag.py
  src/simulation/dynamics/facetDragEffector/facetDragDynamicEffector.cpp
Labels: bug

#488 Feature/487 thruster platform state
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformState/_UnitTest/test_thrusterPlatformState.py
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformState/thrusterPlatformState.c
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformState/thrusterPlatformState.h
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformState/thrusterPlatformState.i
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformState/thrusterPlatformState.rst
Labels: enhancement

#490 Refactor/489 thruster platform reference
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/_UnitTest/test_thrusterPlatformReference.py
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/thrusterPlatformReference.c
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/thrusterPlatformReference.h
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/thrusterPlatformReference.i
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/thrusterPlatformReference.rst
Labels: enhancement, refactor

#493 Feature/492 thrust cm estimation
  docs/source/Support/bskReleaseNotes.rst
  src/CMakeLists.txt
  src/architecture/msgPayloadDefC/CMEstDataMsgPayload.h
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/_UnitTest/test_thrustCMEstimation.py
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/thrustCMEstimation.cpp
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/thrustCMEstimation.h
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/thrustCMEstimation.i
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/thrustCMEstimation.rst
Labels: enhancement

#495 fix issue with scenario script writing Viz binary by default
  examples/scenarioRendezVous.py
Labels: bug

#331 Feature/330 gravity effector refactor
  docs/source/Support/bskReleaseNotes.rst
  examples/OpNavScenarios/modelsOpNav/BSK_OpNavDynamics.py
  examples/scenarioBasicOrbit.py
  examples/scenarioBasicOrbitStream.py
  examples/scenarioDragRendezvous.py
  examples/scenarioFormationMeanOEFeedback.py
  examples/scenarioGroundDownlink.py
  examples/scenarioLagrangePointOrbit.py
  examples/scenarioOrbitMultiBody.py
  examples/scenarioSmallBodyNavUKF.py
  src/simulation/dynamics/FuelTank/_UnitTest/test_mass_depletion.py
  src/simulation/dynamics/HingedRigidBodies/_UnitTest/test_hingedRigidBodyStateEffector.py
  src/simulation/dynamics/LinearSpringMassDamper/_UnitTest/test_linearSpringMassDamper.py
  src/simulation/dynamics/NHingedRigidBodies/_UnitTest/test_nHingedRigidBodyStateEffector.py
  src/simulation/dynamics/RadiationPressure/_UnitTest/test_radiation_pressure_integrated.py
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_UnitTest/test_thruster_integrated_sim.py
  src/simulation/dynamics/VSCMGs/_UnitTest/test_VSCMGStateEffector_integrated.py
  src/simulation/dynamics/_GeneralModuleFiles/gravityEffector.cpp
  src/simulation/dynamics/_GeneralModuleFiles/gravityEffector.h
  src/simulation/dynamics/_GeneralModuleFiles/gravityEffector.rst
  src/simulation/dynamics/_GeneralModuleFiles/gravityModel.h
  src/simulation/dynamics/_GeneralModuleFiles/pointMassGravityModel.cpp
  src/simulation/dynamics/_GeneralModuleFiles/pointMassGravityModel.h
  src/simulation/dynamics/dualHingedRigidBodies/_UnitTest/test_dualhingedRigidBodyStateEffector.py
  src/simulation/dynamics/extForceTorque/_UnitTest/test_extForceTorqueIntegrated.py
  src/simulation/dynamics/gravityEffector/_Documentation/Basilisk-GravityEffector-20170712.pdf
  src/simulation/dynamics/gravityEffector/_Documentation/Basilisk-GravityEffector-20170712.tex
  src/simulation/dynamics/gravityEffector/_Documentation/secModelDescription.tex
  src/simulation/dynamics/gravityEffector/_Documentation/secModelFunctions.tex
  src/simulation/dynamics/gravityEffector/_Documentation/secTest.tex
  src/simulation/dynamics/gravityEffector/_Documentation/secUserGuide.tex
  src/simulation/dynamics/gravityEffector/_UnitTest/test_gravityDynEffector.py
  src/simulation/dynamics/gravityEffector/_UnitTest/test_gravitySpacecraft.py
  src/simulation/dynamics/gravityEffector/gravCoeffOps.py
  src/simulation/dynamics/gravityEffector/gravityEffector.i
  src/simulation/dynamics/gravityEffector/gravityModel.i
  src/simulation/dynamics/gravityEffector/pointMassGravityModel.i
  src/simulation/dynamics/gravityEffector/polyhedralGravityModel.cpp
  src/simulation/dynamics/gravityEffector/polyhedralGravityModel.h
  src/simulation/dynamics/gravityEffector/polyhedralGravityModel.i
  src/simulation/dynamics/gravityEffector/sphericalHarmonicsGravityModel.cpp
  src/simulation/dynamics/gravityEffector/sphericalHarmonicsGravityModel.h
  src/simulation/dynamics/gravityEffector/sphericalHarmonicsGravityModel.i
  src/simulation/dynamics/prescribedMotion/_UnitTest/test_PrescribedMotionStateEffector.py
  src/simulation/dynamics/reactionWheels/_UnitTest/test_reactionWheelStateEffector_integrated.py
  src/simulation/dynamics/spacecraft/_UnitTest/test_spacecraft.py
  src/simulation/dynamics/spacecraft/spacecraft.i
  src/simulation/dynamics/spacecraftSystem/_UnitTest/test_multiSpacecraft.py
  src/simulation/dynamics/spacecraftSystem/spacecraftSystem.i
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/_UnitTest/test_spinningBodyOneDOFStateEffector.py
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/_UnitTest/test_spinningBodyTwoDOFStateEffector.py
  src/utilities/MonteCarlo/_UnitTests/test_scenarioBasicOrbitMC.py
Labels: refactor

#500 Feature/499 Fix SWIG Eigen type maps to remove data leaks
  src/architecture/_GeneralModuleFiles/swig_eigen.i
Labels: bug

#497 Refactor scenario_spinningBodiesTwoDOF
  examples/scenarioSpinningBodiesTwoDOF.py
Labels: enhancement, refactor

#484 Feature/480 Fix tests and examples when built without viz support
  docs/source/Support/bskReleaseNotes.rst
  examples/BskSim/scenarios/scenario_BasicOrbitFormation.py
  examples/BskSim/scenarios/scenario_RelativePointingFormation.py
  examples/scenarioAsteroidArrival.py
  examples/scenarioCustomGravBody.py
  examples/scenarioDataToViz.py
  examples/scenarioDebrisReorbitET.py
  examples/scenarioDeployingPanel.py
  examples/scenarioFlybySpice.py
  examples/scenarioFormationBasic.py
  examples/scenarioGroundLocationImaging.py
  examples/scenarioGroundMapping.py
  examples/scenarioHelioTransSpice.py
  examples/scenarioOrbitManeuver.py
  examples/scenarioRendezVous.py
  examples/scenarioSensorThermal.py
  examples/scenarioSmallBodyFeedbackControl.py
  examples/scenarioSmallBodyNav.py
  examples/scenarioSpacecraftLocation.py
  examples/scenarioSpinningBodiesTwoDOF.py
  examples/scenarioTwoChargedSC.py
  src/simulation/vizard/dataFileToViz/_UnitTest/test_dataFileToViz.py
Labels: bug

#502 Feature/437 build bsk doc
  docs/source/Install.rst
  docs/source/Install/customPython.rst
  docs/source/Install/installBuild.rst
  docs/source/Install/installBuildConan.rst
  docs/source/Install/installOnWindows.rst
  src/architecture/msgPayloadDefC/CMEstDataMsgPayload.h
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/thrustCMEstimation.h
  src/simulation/dynamics/_GeneralModuleFiles/gravityModel.h
Labels: documentation

#504 Adjust the name of the testing function.
  src/tests/test_scenarioSpinningBodiesTwoDOF.py
Labels: bug, refactor

#507 Feature/506 set data buffer method in storage unit
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/onboardDataHandling/_GeneralModuleFiles/dataStorageUnitBase.cpp
  src/simulation/onboardDataHandling/_GeneralModuleFiles/dataStorageUnitBase.h
  src/simulation/onboardDataHandling/_GeneralModuleFiles/dataStorageUnitBase.rst
  src/simulation/onboardDataHandling/storageUnit/_UnitTest/test_partitionedStorageUnit.py
  src/simulation/onboardDataHandling/storageUnit/_UnitTest/test_simpleStorageUnit.py
  src/simulation/onboardDataHandling/storageUnit/partitionedStorageUnit.cpp
  src/simulation/onboardDataHandling/storageUnit/partitionedStorageUnit.h
  src/simulation/onboardDataHandling/storageUnit/partitionedStorageUnit.i
  src/simulation/onboardDataHandling/storageUnit/partitionedStorageUnit.rst
  src/simulation/onboardDataHandling/storageUnit/simpleStorageUnit.cpp
  src/simulation/onboardDataHandling/storageUnit/simpleStorageUnit.h
  src/simulation/onboardDataHandling/storageUnit/simpleStorageUnit.i
  src/simulation/onboardDataHandling/storageUnit/simpleStorageUnit.rst
Labels: enhancement

#509 Refactor/508 change variable in StorageUnit from long int to int64_t
  src/simulation/onboardDataHandling/_GeneralModuleFiles/dataStorageUnitBase.cpp
  src/simulation/onboardDataHandling/_GeneralModuleFiles/dataStorageUnitBase.h
  src/simulation/onboardDataHandling/storageUnit/partitionedStorageUnit.cpp
  src/simulation/onboardDataHandling/storageUnit/partitionedStorageUnit.i
  src/simulation/onboardDataHandling/storageUnit/simpleStorageUnit.cpp
  src/simulation/onboardDataHandling/storageUnit/simpleStorageUnit.h
  src/simulation/onboardDataHandling/storageUnit/simpleStorageUnit.i
Labels: enhancement

#517 516 thrust cm estimation bug fix
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/thrustCMEstimation.cpp
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/thrustCMEstimation.rst
Labels: bug
