Repository AVSLab/basilisk, pull requests merged in 2023-04, with the labels that each got.

#278 Feature/276 change integrator after sync
  docs/source/Learn/bskPrinciples/bskPrinciples-9.rst
  examples/scenarioFormationBasic.py
  src/simulation/dynamics/_GeneralModuleFiles/dynamicObject.cpp
  src/simulation/dynamics/_GeneralModuleFiles/dynamicObject.h
Labels: bug

#285 Feature/fix misc issues
  conanfile.py
  docs/source/Learn/bskPrinciples/bskPrinciples-4.rst
  src/architecture/utilities/linearAlgebra.c
  src/architecture/utilities/linearAlgebra.h
  src/fswAlgorithms/formationFlying/meanOEFeedback/_UnitTest/test_meanOEFeedback.py
  src/simulation/dynamics/DynOutput/orbElemConvert/_UnitTest/test_orb_elem_convert.py
  src/simulation/environment/eclipse/eclipse.cpp
Labels: bug

#125 Prescribed rot1 dof refactor
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/effectorInterfaces/prescribedRot1DOF/_UnitTest/test_prescribedRot1DOF.py
Labels: refactor

#299 Feature/zmq 4 5 0
  conanfile.py
  docs/source/Support/bskReleaseNotes.rst
Labels: bug

#296 Advance project C++ standard from C++11 to C++17
  docs/source/Support/bskReleaseNotes.rst
  src/CMakeLists.txt
Labels: build

#290 Disable unused opencv build flags
  conanfile.py
  docs/source/Support/bskReleaseNotes.rst
Labels: build

#300 SmallBodyNavEKF Improvements
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioSmallBodyNav.py
  src/architecture/msgPayloadDefC/SmallBodyNavMsgPayload.h
  src/fswAlgorithms/smallBodyNavigation/smallBodyNavEKF/_Documentation/Images/moduleIOSmallBodyNavigation.svg
  src/fswAlgorithms/smallBodyNavigation/smallBodyNavEKF/_UnitTest/test_smallBodyNavEKF.py
  src/fswAlgorithms/smallBodyNavigation/smallBodyNavEKF/smallBodyNavEKF.cpp
  src/fswAlgorithms/smallBodyNavigation/smallBodyNavEKF/smallBodyNavEKF.h
  src/fswAlgorithms/smallBodyNavigation/smallBodyNavEKF/smallBodyNavEKF.i
  src/fswAlgorithms/smallBodyNavigation/smallBodyNavEKF/smallBodyNavEKF.rst
Labels: enhancement

#309 Incorrect radii assignments in eclipse module.
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/environment/eclipse/eclipse.cpp
Labels: bug
