Repository AVSLab/basilisk, pull requests merged in 2023-06, with the labels that each got.

#361 Fixes C msg read error
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioGroundLocationImaging.py
  examples/scenarioGroundMapping.py
  examples/scenarioMomentumDumping.py
  examples/scenarioSensorThermal.py
  src/fswAlgorithms/attDetermination/sunlineSuKF/sunlineSuKF.c
  src/fswAlgorithms/effectorInterfaces/thrMomentumDumping/thrMomentumDumping.c
Labels: bug

#354 Feature/fix geodetic conversion
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/utilities/geodeticConversion.cpp
  src/architecture/utilities/geodeticConversion.h
  src/architecture/utilities/tests/CMakeLists.txt
  src/architecture/utilities/tests/test_geodeticConversion.cpp
Labels: bug

#366 fix RST documentation issue
  src/architecture/utilities/geodeticConversion.cpp
Labels: bug, documentation

#365 Update daylight savings issue in environment base classes
  run_all_test.py
  src/simulation/environment/MsisAtmosphere/_UnitTest/test_msiseAtmosphere.py
  src/simulation/environment/_GeneralModuleFiles/atmosphereBase.cpp
  src/simulation/environment/_GeneralModuleFiles/magneticFieldBase.cpp
Labels: bug

#374 Fix message members python bool types returned as empty dict
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/messaging/newMessaging.ih
Labels: bug

#275 Prescribed Motion module refactor
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/prescribedMotion/_UnitTest/test_PrescribedMotionStateEffector.py
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.cpp
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.h
Labels: refactor

#382 Feature/viz 2 1 5 support
  docs/source/Vizard/Vizard.rst
  docs/source/Vizard/VizardDownload.rst
  docs/source/Vizard/VizardReleaseNotes.rst
  docs/source/Vizard/assetAsteroids.rst
  docs/source/Vizard/assetMartianMoons.rst
  docs/source/Vizard/vizardAdvanced/vizardCommandLine.rst
  docs/source/Vizard/vizardAdvanced/vizardSettings.rst
  examples/scenarioIntegrators.py
  src/architecture/msgPayloadDefC/CameraConfigMsgPayload.h
  src/simulation/dynamics/Integrators/_UnitTest/test_Integrators.py
  src/simulation/vizard/_GeneralModuleFiles/vizStructures.h
  src/simulation/vizard/vizInterface/vizInterface.cpp
  src/utilities/vizProtobuffer/vizMessage.proto
  src/utilities/vizSupport.py
Labels: documentation, enhancement

#383 Feature/bsk 2 2 0
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskVersion.txt
Labels: documentation

#384 Feature/bsk 2 2 1 beta
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskVersion.txt
Labels: documentation
