Repository AVSLab/basilisk, pull requests merged in 2023-01, with the labels that each got.

#70 Feature/bsk 69 fix hub position in thruster module
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_UnitTest/test_ThrusterDynamicsUnit.py
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/thrusterDynamicEffector.cpp
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/thrusterDynamicEffector.h
  src/simulation/dynamics/Thrusters/thrusterStateEffector/thrusterStateEffector.cpp
  src/simulation/dynamics/Thrusters/thrusterStateEffector/thrusterStateEffector.h
Labels: bug

#78 Conan dependency and vizInterface CMake updates
  conanfile.py
  docs/source/Support/bskReleaseNotes.rst
  src/cmake/FindProtobuf.cmake
  src/cmake/usingProtobuf.cmake
  src/cmake/usingZMQ.cmake
  src/simulation/vizard/vizInterface/Custom.cmake
  src/utilities/vizProtobuffer/CMakeLists.txt
Labels: enhancement

#79 Feature/63 unused msgheader pointer in recorder constructor
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/messaging/_UnitTest/test_CMsgTimeWritten.py
  src/architecture/messaging/messaging.h
  src/architecture/messaging/msgAutoSource/cMsgCInterfacePy.i.in
  src/architecture/messaging/msgAutoSource/msg_C.cpp.in
  src/architecture/messaging/msgAutoSource/msg_C.h.in
  src/architecture/messaging/msgHeader.h
Labels: bug

#100 Feature/bsk 99 docs lfs
  docs/source/Install/pullCloneBSK.rst
  docs/source/Support/bskReleaseNotes.rst
Labels: documentation

#105 Feature/bsk 104 viz ground location
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioGroundLocationImaging.py
Labels: bug

#98 Add conversion from C array to MRPd
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/utilities/avsEigenSupport.cpp
  src/architecture/utilities/avsEigenSupport.h
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/thrusterDynamicEffector.cpp
  src/simulation/dynamics/Thrusters/thrusterStateEffector/thrusterStateEffector.cpp
  src/simulation/dynamics/spacecraft/spacecraft.cpp
  src/simulation/environment/spacecraftLocation/spacecraftLocation.cpp
  src/simulation/power/simpleSolarPanel/simpleSolarPanel.cpp
  src/simulation/sensors/coarseSunSensor/coarseSunSensor.cpp
  src/simulation/sensors/magnetometer/magnetometer.cpp
Labels: enhancement, refactor

#112 Feature/bsk 111 update spinning body msg
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/msgPayloadDefC/SpinningBodyMsgPayload.h
  src/simulation/dynamics/HingedRigidBodies/hingedRigidBodyStateEffector.rst
  src/simulation/dynamics/spinningBodies/spinningBodyStateEffector.cpp
  src/simulation/dynamics/spinningBodies/spinningBodyStateEffector.h
  src/simulation/dynamics/spinningBodies/spinningBodyStateEffector.i
  src/simulation/dynamics/spinningBodies/spinningBodyStateEffector.rst
Labels: bug

#102 Inertial heading in boreAngCalc
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/DynOutput/boreAngCalc/_Documentation/Basilisk-BOREANGLECALC-20170722.bbl
  src/simulation/dynamics/DynOutput/boreAngCalc/_Documentation/Basilisk-BOREANGLECALC-20170722.pdf
  src/simulation/dynamics/DynOutput/boreAngCalc/_Documentation/Basilisk-BOREANGLECALC-20170722.tex
  src/simulation/dynamics/DynOutput/boreAngCalc/_Documentation/secModelDescription.tex
  src/simulation/dynamics/DynOutput/boreAngCalc/_Documentation/secModelFunctions.tex
  src/simulation/dynamics/DynOutput/boreAngCalc/_Documentation/secTest.tex
  src/simulation/dynamics/DynOutput/boreAngCalc/_Documentation/secUserGuide.tex
  src/simulation/dynamics/DynOutput/boreAngCalc/_UnitTest/test_bore_ang_calc.py
  src/simulation/dynamics/DynOutput/boreAngCalc/_UnitTest/test_bore_ang_calc_inertial_heading.py
  src/simulation/dynamics/DynOutput/boreAngCalc/boreAngCalc.cpp
  src/simulation/dynamics/DynOutput/boreAngCalc/boreAngCalc.h
  src/simulation/dynamics/DynOutput/boreAngCalc/boreAngCalc.i
  src/simulation/dynamics/DynOutput/boreAngCalc/boreAngCalc.rst
Labels: enhancement, refactor

#132 Feature/bsk 80 vizard 2 1 3
  docs/source/Support/bskReleaseNotes.rst
  docs/source/Vizard/Vizard.rst
  docs/source/Vizard/VizardReleaseNotes.rst
  docs/source/Vizard/vizardAdvanced/vizardSettings.rst
  examples/scenarioDebrisReorbitET.py
  src/simulation/vizard/_GeneralModuleFiles/vizStructures.h
  src/simulation/vizard/vizInterface/vizInterface.cpp
  src/utilities/vizProtobuffer/vizMessage.proto
  src/utilities/vizSupport.py
Labels: enhancement

#107 Feature/bsk 103 imaging rate limit
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/sensorInterfaces/simpleInstrumentController/_UnitTest/test_simpleInstrumentController.py
  src/fswAlgorithms/sensorInterfaces/simpleInstrumentController/simpleInstrumentController.c
  src/fswAlgorithms/sensorInterfaces/simpleInstrumentController/simpleInstrumentController.h
  src/fswAlgorithms/sensorInterfaces/simpleInstrumentController/simpleInstrumentController.rst
Labels: enhancement

#147 New Basilisk tagged release
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskVersion.txt
Labels: documentation

#148 prepare for next beta cycle
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskVersion.txt
Labels: documentation

#116 Feature/bsk 106 hinged rigid body PID motor
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/effectorInterfaces/hingedRigidBodyPIDMotor/_UnitTest/test_hingedRigidBodyPIDMotor.py
  src/fswAlgorithms/effectorInterfaces/hingedRigidBodyPIDMotor/hingedRigidBodyPIDMotor.c
  src/fswAlgorithms/effectorInterfaces/hingedRigidBodyPIDMotor/hingedRigidBodyPIDMotor.h
  src/fswAlgorithms/effectorInterfaces/hingedRigidBodyPIDMotor/hingedRigidBodyPIDMotor.i
  src/fswAlgorithms/effectorInterfaces/hingedRigidBodyPIDMotor/hingedRigidBodyPIDMotor.rst
Labels: enhancement

#149 Feature/bsk 143 torque scheduler
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/msgPayloadDefC/ArrayEffectorLockMsgPayload.h
  src/fswAlgorithms/effectorInterfaces/torqueScheduler/_UnitTest/test_torqueScheduler.py
  src/fswAlgorithms/effectorInterfaces/torqueScheduler/torqueScheduler.c
  src/fswAlgorithms/effectorInterfaces/torqueScheduler/torqueScheduler.h
  src/fswAlgorithms/effectorInterfaces/torqueScheduler/torqueScheduler.i
  src/fswAlgorithms/effectorInterfaces/torqueScheduler/torqueScheduler.rst
Labels: enhancement

#152 add missing structure variable definition
  src/fswAlgorithms/effectorInterfaces/torqueScheduler/torqueScheduler.h
Labels: documentation

#159 Feature/bsk 128 save figure pdf fix
  docs/source/Support/bskReleaseNotes.rst
  src/utilities/unitTestSupport.py
Labels: bug

#156 This commit creates the sensorThermal module
  docs/source/Support/bskReleaseNotes.rst
  examples/_default.rst
  examples/scenarioSensorThermal.py
  src/simulation/thermal/sensorThermal/_UnitTest/test_sensorThermal.py
  src/simulation/thermal/sensorThermal/sensorThermal.cpp
  src/simulation/thermal/sensorThermal/sensorThermal.h
  src/simulation/thermal/sensorThermal/sensorThermal.i
  src/simulation/thermal/sensorThermal/sensorThermal.rst
  src/tests/test_scenarioTest.py
Labels: enhancement
