Repository AVSLab/basilisk, pull requests merged in 2024-02, with the labels that each got.

#589 Bump version number with bot
  .github/workflows/pull-request-closed.yml
Labels: ci

#595 Feature/fix opnav plotting
  docs/source/Support/bskReleaseNotes.rst
  examples/OpNavScenarios/plottingOpNav/OpNav_Plotting.py
Labels: bug

#587 Address compiler warnings
  docs/source/Learn/makingModules/cppModules/cppModules-4.rst
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/gravityEffector/polyhedralGravityModel.h
  src/simulation/dynamics/gravityEffector/sphericalHarmonicsGravityModel.cpp
  src/simulation/dynamics/gravityEffector/sphericalHarmonicsGravityModel.h
  src/simulation/environment/spiceInterface/spiceInterface.cpp
Labels: bug

#599 Refactor/refactor prescribed trans msg
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/msgPayloadDefC/LinearTranslationRigidBodyMsgPayload.h
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/_UnitTest/test_prescribedTrans.py
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/prescribedTrans.c
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/prescribedTrans.h
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/prescribedTrans.i
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/prescribedTrans.rst
  src/simulation/dynamics/prescribedMotion/_UnitTest/test_PrescribedMotionStateEffector.py
Labels: refactor

#606 New halo example script
  docs/source/Support/bskReleaseNotes.rst
  examples/_default.rst
  examples/scenarioHaloOrbit.py
  src/tests/test_scenarioTest.py
Labels: enhancement

#602 Feature/swig 4 2
  docs/source/Install/installOnLinux.rst
  docs/source/Install/installOnMacOS.rst
  docs/source/Install/installOnWindows.rst
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/_GeneralModuleFiles/swig_common_model.i
  src/architecture/messaging/msgAutoSource/msgInterfacePy.i.in
  src/architecture/messaging/newMessaging.ih
  src/architecture/system_model/sim_model.i
  src/architecture/system_model/sys_model_task.i
  src/architecture/utilities/bskUtilities.i
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/thrusterDynamicEffector.i
  src/simulation/dynamics/reactionWheels/reactionWheelStateEffector.i
  src/simulation/sensors/coarseSunSensor/coarseSunSensor.i
  src/simulation/vizard/dataFileToViz/dataFileToViz.i
Labels: bug, documentation, build
