Repository AVSLab/basilisk, pull requests merged in 2024-08, with the labels that each got.

#759 Bug/thruster state effector isp factor
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/FuelTank/_UnitTest/test_mass_depletion.py
  src/simulation/dynamics/Thrusters/thrusterStateEffector/_UnitTest/test_ThrusterStateEffectorUnit.py
  src/simulation/dynamics/Thrusters/thrusterStateEffector/thrusterStateEffector.cpp
Labels: bug

#751 Feature/743 solar array reference update
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/_UnitTest/test_solarArrayReference.py
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/solarArrayReference.c
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/solarArrayReference.h
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/solarArrayReference.i
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/solarArrayReference.rst
Labels: enhancement

#737 Support for `pip install` as a standard Python package
  .gitignore
  conanfile.py
  docs/source/Install.rst
  docs/source/Install/pipInstall.rst
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioSepMomentumManagement.py
  pyproject.toml
  requirements.txt
  setup.py
  src/CMakeLists.txt
  src/architecture/messaging/CMakeLists.txt
  src/architecture/messaging/cMsgCInterface/CMakeLists.txt
  src/architecture/messaging/cMsgCInterfacePy/__init__.py
  src/architecture/messaging/msgAutoSource/generatePackageInit.py
  src/simulation/environment/TabularAtmosphere/_UnitTest/test_unitTestTabularAtmosphere.py
  src/utilities/MonteCarlo/__init__.py
  src/utilities/__init__.py
Labels: build

#734 add CI tests for all compatible python versions
  .github/workflows/pull-request.yml
  conanfile.py
  docs/source/Install/installOnLinux.rst
  docs/source/Install/installOnMacOS.rst
  docs/source/Install/installOnWindows.rst
  docs/source/Install/pipInstall.rst
  docs/source/Support/bskReleaseNotes.rst
  pyproject.toml
  requirements.txt
Labels: documentation, ci

#720 Have effector receive hub state and parameter names automatically
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioAlbedo.py
  examples/scenarioAsteroidArrival.py
  examples/scenarioHohmann.py
  examples/scenarioJupiterArrival.py
  examples/scenarioOrbitManeuver.py
  examples/scenarioPatchedConics.py
  examples/scenarioRendezVous.py
  src/simulation/dynamics/FuelTank/_UnitTest/test_mass_depletion.py
  src/simulation/dynamics/FuelTank/fuelTank.cpp
  src/simulation/dynamics/GravityGradientEffector/GravityGradientEffector.cpp
  src/simulation/dynamics/HingedRigidBodies/hingedRigidBodyStateEffector.cpp
  src/simulation/dynamics/HingedRigidBodies/hingedRigidBodyStateEffector.h
  src/simulation/dynamics/LinearSpringMassDamper/_UnitTest/test_linearSpringMassDamper.py
  src/simulation/dynamics/LinearSpringMassDamper/linearSpringMassDamper.cpp
  src/simulation/dynamics/LinearSpringMassDamper/linearSpringMassDamper.h
  src/simulation/dynamics/MtbEffector/MtbEffector.cpp
  src/simulation/dynamics/NHingedRigidBodies/nHingedRigidBodyStateEffector.cpp
  src/simulation/dynamics/NHingedRigidBodies/nHingedRigidBodyStateEffector.h
  src/simulation/dynamics/RadiationPressure/radiationPressure.cpp
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_UnitTest/test_ThrusterDynamicsUnit.py
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_UnitTest/test_thruster_integrated_sim.py
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/thrusterDynamicEffector.cpp
  src/simulation/dynamics/Thrusters/thrusterStateEffector/thrusterStateEffector.cpp
  src/simulation/dynamics/VSCMGs/_UnitTest/test_VSCMGStateEffector_integrated.py
  src/simulation/dynamics/VSCMGs/vscmgStateEffector.cpp
  src/simulation/dynamics/VSCMGs/vscmgStateEffector.h
  src/simulation/dynamics/_GeneralModuleFiles/dynParamManager.cpp
  src/simulation/dynamics/_GeneralModuleFiles/dynamicEffector.cpp
  src/simulation/dynamics/_GeneralModuleFiles/dynamicEffector.h
  src/simulation/dynamics/_GeneralModuleFiles/stateEffector.cpp
  src/simulation/dynamics/_GeneralModuleFiles/stateEffector.h
  src/simulation/dynamics/dragEffector/dragDynamicEffector.cpp
  src/simulation/dynamics/dualHingedRigidBodies/dualHingedRigidBodyStateEffector.cpp
  src/simulation/dynamics/dualHingedRigidBodies/dualHingedRigidBodyStateEffector.h
  src/simulation/dynamics/extForceTorque/_UnitTest/test_extForceTorqueIntegrated.py
  src/simulation/dynamics/facetDragEffector/facetDragDynamicEffector.cpp
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.cpp
  src/simulation/dynamics/gravityEffector/_UnitTest/test_gravityDynEffector.py
  src/simulation/dynamics/gravityEffector/_UnitTest/test_gravitySpacecraft.py
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesOneDOF/linearTranslationOneDOFStateEffector.cpp
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.cpp
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.h
  src/simulation/dynamics/reactionWheels/reactionWheelStateEffector.cpp
  src/simulation/dynamics/reactionWheels/reactionWheelStateEffector.h
  src/simulation/dynamics/spacecraft/spacecraft.cpp
  src/simulation/dynamics/spacecraft/spacecraft.h
  src/simulation/dynamics/spacecraftSystem/spacecraftSystem.cpp
  src/simulation/dynamics/spacecraftSystem/spacecraftSystem.h
  src/simulation/dynamics/sphericalPendulum/_UnitTest/test_sphericalPendulum.py
  src/simulation/dynamics/sphericalPendulum/sphericalPendulum.cpp
  src/simulation/dynamics/sphericalPendulum/sphericalPendulum.h
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/spinningBodyOneDOFStateEffector.cpp
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/spinningBodyTwoDOFStateEffector.cpp
Labels: enhancement

#752 Reduced rebuild times by reimplementing `GenCMessages` and fixing `vizInterface` dependencies in CMake
  conanfile.py
  docs/source/Learn/makingModules/makingModules-2.rst
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/messaging/CMakeLists.txt
  src/architecture/messaging/cMsgCInterface/CMakeLists.txt
  src/architecture/messaging/cMsgCInterface/msg_C.cpp.in
  src/architecture/messaging/cMsgCInterface/msg_C.h.in
  src/architecture/messaging/msgAutoSource/GenCMessages.py
  src/architecture/messaging/msgAutoSource/README.in
  src/architecture/messaging/msgAutoSource/msg_C.h.in
  src/utilities/vizProtobuffer/CMakeLists.txt
Labels: build

#686 Vizard 2.2.0 support
  docs/source/Support/bskReleaseNotes.rst
  docs/source/Vizard/Vizard.rst
  docs/source/Vizard/VizardDownload.rst
  docs/source/Vizard/VizardGUI.rst
  docs/source/Vizard/VizardReleaseNotes.rst
  docs/source/Vizard/assetAsteroids.rst
  docs/source/Vizard/vizardAdvanced/index.rst
  docs/source/Vizard/vizardAdvanced/vizardCommandLine.rst
  docs/source/Vizard/vizardAdvanced/vizardCustomModels.rst
  docs/source/Vizard/vizardAdvanced/vizardLiveComm.rst
  docs/source/Vizard/vizardAdvanced/vizardSettings.rst
  docs/source/Vizard/vizardGallery.rst
  docs/source/_images/static/vizard-Img2.jpg
  docs/source/index.rst
  examples/OpNavScenarios/BSK_OpNav.py
  examples/OpNavScenarios/modelsOpNav/BSK_OpNavDynamics.py
  examples/OpNavScenarios/plottingOpNav/OpNav_Plotting.py
  examples/OpNavScenarios/scenariosOpNav/CNN_ImageGen/scenario_CNNImages.py
  examples/OpNavScenarios/scenariosOpNav/scenario_CNNAttOD.py
  examples/OpNavScenarios/scenariosOpNav/scenario_OpNavAttOD.py
  examples/OpNavScenarios/scenariosOpNav/scenario_OpNavAttODLimb.py
  examples/OpNavScenarios/scenariosOpNav/scenario_OpNavHeading.py
  examples/OpNavScenarios/scenariosOpNav/scenario_OpNavOD.py
  examples/OpNavScenarios/scenariosOpNav/scenario_OpNavODLimb.py
  examples/OpNavScenarios/scenariosOpNav/scenario_OpNavPoint.py
  examples/OpNavScenarios/scenariosOpNav/scenario_OpNavPointLimb.py
  examples/OpNavScenarios/scenariosOpNav/scenario_faultDetOpNav.py
  examples/scenarioBasicOrbitStream.py
  examples/scenarioCustomGravBody.py
  src/architecture/msgPayloadDefCpp/VizUserInputMsgPayload.h
  src/fswAlgorithms/imageProcessing/horizonOpNav/horizonOpNav.c
  src/simulation/vizard/_GeneralModuleFiles/vizStructures.h
  src/simulation/vizard/vizInterface/vizInterface.cpp
  src/simulation/vizard/vizInterface/vizInterface.h
  src/simulation/vizard/vizInterface/vizInterface.i
  src/simulation/vizard/vizInterface/vizInterface.rst
  src/tests/test_scenarioBasicOrbitStream.py
  src/utilities/vizProtobuffer/vizMessage.proto
  src/utilities/vizSupport.py
Labels: enhancement

#770 make CI chache names unique to Linux OS
  .github/workflows/pull-request.yml
Labels: bug, build

#652 Feature/466 running non swig v2
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/messaging/_UnitTest/test_NonSwigMessaging.py
  src/architecture/messaging/cMsgCInterface/msg_C.cpp.in
  src/architecture/messaging/cMsgCInterface/msg_C.h.in
  src/architecture/messaging/messaging.h
  src/architecture/messaging/msgAutoSource/cMsgCInterfacePy.i.in
  src/architecture/utilities/bskLogging.cpp
Labels: enhancement

#774 Feature/bsk 2 4 0
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskVersion.txt
Labels: documentation

#775 Prepare for next 2.4.x beta cycle
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
Labels: documentation

#773 Fix bug in simIncludeRW.py on setting Js value
  docs/source/Support/bskKnownIssues.rst
  src/simulation/dynamics/reactionWheels/_UnitTest/test_reactionWheelStateEffector_integrated.py
  src/utilities/simIncludeRW.py
Labels: bug

#772 Feature/771 adding swirl torque
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/msgPayloadDefC/THRConfigMsgPayload.h
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformState/_UnitTest/test_thrusterPlatformState.py
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformState/thrusterPlatformState.c
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/thrustCMEstimation.cpp
Labels: enhancement

#778 Fix "invalid command `bdist_wheel`" errors during some Conanfile-based installs
  .github/workflows/pull-request.yml
  conanfile.py
  docs/source/Support/bskReleaseNotes.rst
  pyproject.toml
  src/architecture/messaging/CMakeLists.txt
Labels: build

#782 Re-download `de430.bsp` if it gets interrupted
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/CMakeLists.txt
Labels: enhancement, build

#780 Modernize core BSK architecture CPP files
  src/architecture/_GeneralModuleFiles/sys_model.h
  src/architecture/system_model/sim_model.cpp
  src/architecture/system_model/sim_model.h
  src/architecture/system_model/sys_model_task.cpp
  src/architecture/system_model/sys_model_task.h
  src/architecture/system_model/sys_process.cpp
  src/architecture/system_model/sys_process.h
Labels: enhancement

#768 Feature/fuel tank blow down
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/msgPayloadDefCpp/THROutputMsgPayload.h
  src/simulation/dynamics/FuelTank/fuelTank.cpp
  src/simulation/dynamics/FuelTank/fuelTank.h
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_Documentation/Basilisk-THRUSTERS20170712.pdf
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_Documentation/Basilisk-THRUSTERS20170712.tex
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_Documentation/secModelDescription.tex
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_Documentation/secModelFunctions.tex
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_Documentation/secTest.tex
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_Documentation/secUserGuide.tex
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_UnitTest/test_ThrusterDynamicsUnit.py
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_UnitTest/test_thruster_integrated_sim.py
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/thrusterDynamicEffector.cpp
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/thrusterDynamicEffector.h
  src/simulation/dynamics/_GeneralModuleFiles/THROperation.h
  src/simulation/dynamics/_GeneralModuleFiles/THRSimConfig.h
  src/utilities/simIncludeThruster.py
Labels: enhancement

#784 vizInterface not saving binary file
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/system_model/sys_process.cpp
  src/simulation/vizard/vizInterface/vizInterface.cpp
Labels: bug
