Repository AVSLab/basilisk, pull requests merged in 2024-01, with the labels that each got.

#557 Treat python version as string, rather than float, to accommodate python >=3.10
  conanfile.py
Labels: bug

#560 correct import statement in bskLogger documentation
  src/architecture/utilities/bskLogging.rst
Labels: documentation

#550 Feature/498 add srp effector facet articulation
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioSepMomentumManagement.py
  src/simulation/dynamics/facetSRPDynamicEffector/_UnitTest/test_unitFacetSRPDynamicEffector.py
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.cpp
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.h
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.rst
Labels: enhancement

#563 be explicit about installing the latest 1.x version of conan
  docs/source/Install/installOnLinux.rst
  docs/source/Install/installOnMacOS.rst
  docs/source/Install/installOnWindows.rst
Labels: documentation

#573 Cancel workflow for invalidated branch
  .github/workflows/pull-request.yml
Labels: ci

#584 suppress depreciation warning of legacy code testing
  src/utilities/tests/test_legacyVariableLogging.py
Labels: bug

#585 Fix version comparison operator
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/CMakeLists.txt
Labels: bug
