Repository AVSLab/basilisk, pull requests merged in 2024-03, with the labels that each got.

#624 fix DCM variable description.
  src/simulation/sensors/coarseSunSensor/coarseSunSensor.h
Labels: documentation

#626 Add Support for Vizard 2.1.6 release
  docs/source/Support/bskReleaseNotes.rst
  docs/source/Vizard/Vizard.rst
  docs/source/Vizard/VizardReleaseNotes.rst
  docs/source/Vizard/vizardAdvanced/vizardSettings.rst
  src/simulation/vizard/_GeneralModuleFiles/vizStructures.h
  src/simulation/vizard/vizInterface/vizInterface.cpp
  src/utilities/vizProtobuffer/vizMessage.proto
Labels: enhancement

#588 Port prescribedTrans module to C++ with coast profiler
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/prescribedTrans.rst
  src/simulation/deviceInterface/prescribedLinearTranslation/_UnitTest/test_prescribedLinearTranslation.py
  src/simulation/deviceInterface/prescribedLinearTranslation/prescribedLinearTranslation.cpp
  src/simulation/deviceInterface/prescribedLinearTranslation/prescribedLinearTranslation.h
  src/simulation/deviceInterface/prescribedLinearTranslation/prescribedLinearTranslation.i
  src/simulation/deviceInterface/prescribedLinearTranslation/prescribedLinearTranslation.rst
  src/simulation/dynamics/prescribedMotion/_UnitTest/test_PrescribedMotionStateEffector.py
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.rst
Labels: enhancement

#597 Port prescribedRot1DOF module to C++ with coast profiler
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/effectorInterfaces/prescribedRot1DOF/prescribedRot1DOF.rst
  src/simulation/deviceInterface/prescribedRotation1DOF/_UnitTest/test_prescribedRotation1DOF.py
  src/simulation/deviceInterface/prescribedRotation1DOF/prescribedRotation1DOF.cpp
  src/simulation/deviceInterface/prescribedRotation1DOF/prescribedRotation1DOF.h
  src/simulation/deviceInterface/prescribedRotation1DOF/prescribedRotation1DOF.i
  src/simulation/deviceInterface/prescribedRotation1DOF/prescribedRotation1DOF.rst
  src/simulation/dynamics/prescribedMotion/_UnitTest/test_PrescribedMotionStateEffector.py
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.rst
Labels: enhancement

#629 Feature/bsk 611 solar array deployment scenario
  docs/source/Support/bskReleaseNotes.rst
  docs/source/_images/static/scenarioDeployingSolarArrays.jpg
  examples/_default.rst
  examples/dataForExamples/triangularPanel.obj
  examples/scenarioDeployingSolarArrays.py
  src/simulation/deviceInterface/prescribedRotation1DOF/prescribedRotation1DOF.rst
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.rst
  src/tests/test_scenarioTest.py
Labels: enhancement

#638 latest python packages create new depreciation warnings
  examples/scenarioDeployingSolarArrays.py
  src/utilities/readAtmTable.py
Labels: bug, documentation

#641 Fix plot list description in scenarioDeployingSolarArrays
  examples/scenarioDeployingSolarArrays.py
Labels: documentation

#651 Support Vizard 2.1.6.1 release
  docs/source/Support/bskReleaseNotes.rst
  docs/source/Vizard/Vizard.rst
  docs/source/Vizard/VizardReleaseNotes.rst
Labels: documentation

#650 Small fixes to MTB module
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/MtbEffector/MtbEffector.i
  src/simulation/dynamics/MtbEffector/MtbEffector.rst
Labels: bug, documentation

#649 Feature/bsk 613 smooth translational profiler
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/deviceInterface/prescribedLinearTranslation/_UnitTest/test_prescribedLinearTranslation.py
  src/simulation/deviceInterface/prescribedLinearTranslation/prescribedLinearTranslation.cpp
  src/simulation/deviceInterface/prescribedLinearTranslation/prescribedLinearTranslation.h
  src/simulation/deviceInterface/prescribedLinearTranslation/prescribedLinearTranslation.rst
Labels: enhancement

#639 Feature/1 dof translation
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/msgPayloadDefC/ArrayMotorForceMsgPayload.h
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesOneDOF/_UnitTest/test_linearTranslationOneDOFStateEffector.py
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesOneDOF/linearTranslationOneDOFStateEffector.cpp
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesOneDOF/linearTranslationOneDOFStateEffector.h
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesOneDOF/linearTranslationOneDOFStateEffector.i
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesOneDOF/linearTranslationOneDOFStateEffector.rst
Labels: enhancement
