Repository AVSLab/basilisk, pull requests merged in 2024-05, with the labels that each got.

#660 Feature/n dof spinning bodies
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/spinningBodies/spinningBodiesNDOF/_UnitTest/test_spinningBodyNDOFStateEffector.py
  src/simulation/dynamics/spinningBodies/spinningBodiesNDOF/spinningBodyNDOFStateEffector.cpp
  src/simulation/dynamics/spinningBodies/spinningBodiesNDOF/spinningBodyNDOFStateEffector.h
  src/simulation/dynamics/spinningBodies/spinningBodiesNDOF/spinningBodyNDOFStateEffector.i
  src/simulation/dynamics/spinningBodies/spinningBodiesNDOF/spinningBodyNDOFStateEffector.rst
Labels: enhancement

#683 Add example script illustrating use of temperature measurement with noise
  docs/source/Support/bskReleaseNotes.rst
  examples/_default.rst
  examples/scenarioTempMeasurementAttitude.py
  src/tests/test_scenarioTest.py
Labels: enhancement

#679 Set _use_math_macro in compiler for windows
  docs/source/Support/bskReleaseNotes.rst
  src/CMakeLists.txt
  src/architecture/utilities/astroConstants.h
  src/architecture/utilities/geodeticConversion.h
  src/fswAlgorithms/attGuidance/celestialTwoBodyPoint/celestialTwoBodyPoint.c
  src/simulation/dynamics/FuelTank/fuelTank.h
  src/simulation/dynamics/sphericalPendulum/sphericalPendulum.cpp
Labels: build

#687 Update GitHub action
  .github/workflows/pull-request-closed.yml
Labels: ci

#694 AVS Eigen Library Identity MRP Fix
  src/architecture/utilities/avsEigenMRP.h
Labels: bug

#696 Add test to MRP Identity() method
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/utilities/avsEigenMRP.h
  src/architecture/utilities/tests/CMakeLists.txt
  src/architecture/utilities/tests/test_avsEigenMRP.cpp
Labels: enhancement

#691 Fix bug #690: Write epoch string for SPICE with microsecond precision instead of 0.1 second
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/environment/spiceInterface/_UnitTest/test_unitSpice.py
  src/simulation/environment/spiceInterface/spiceInterface.cpp
Labels: bug

#697 Add BSK requirements files
  .github/workflows/pull-request.yml
  conanfile.py
  docs/source/Install/installOnLinux.rst
  docs/source/Install/installOnMacOS.rst
  docs/source/Install/installOnWindows.rst
  docs/source/Install/installOptionalPackages.rst
  docs/source/bskPkgOptions.txt
  docs/source/bskPkgRequired.txt
  requirements.txt
  requirements_optional.txt
Labels: documentation

#689 Make fuel tank models C++ classes
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  examples/MultiSatBskSim/modelsMultiSat/BSK_MultiSatDynamics.py
  examples/scenarioFuelSlosh.py
  src/simulation/dynamics/FuelTank/_Documentation/Basilisk-FUELTANK-20171203.pdf
  src/simulation/dynamics/FuelTank/_Documentation/Basilisk-FUELTANK-20171203.tex
  src/simulation/dynamics/FuelTank/_Documentation/secModelFunctions.tex
  src/simulation/dynamics/FuelTank/_Documentation/secTest.tex
  src/simulation/dynamics/FuelTank/_UnitTest/test_mass_depletion.py
  src/simulation/dynamics/FuelTank/_UnitTest/test_tank_models.py
  src/simulation/dynamics/FuelTank/fuelTank.cpp
  src/simulation/dynamics/FuelTank/fuelTank.h
  src/simulation/dynamics/FuelTank/fuelTank.rst
  src/simulation/dynamics/LinearSpringMassDamper/_UnitTest/test_linearSpringMassDamper.py
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_UnitTest/test_thruster_integrated_sim.py
  src/simulation/dynamics/sphericalPendulum/_UnitTest/test_sphericalPendulum.py
Labels: enhancement

#703 Update to latest sphinx and sphinx_rtd_theme
  docs/source/Forum.rst
  docs/source/Install/installOptionalPackages.rst
  docs/source/Support/bskReleaseNotes.rst
  docs/source/_static/css/custom.css
  docs/source/conf.py
  requirements_optional.txt
Labels: documentation

#698 add time tag to CSS measurement message
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/msgPayloadDefC/CSSArraySensorMsgPayload.h
  src/simulation/sensors/coarseSunSensor/coarseSunSensor.cpp
Labels: enhancement

#699 Update conanfile
  conanfile.py
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/imageProcessing/centerRadiusCNN/centerRadiusCNN.cpp
  src/simulation/dynamics/spacecraft/spacecraft.cpp
  src/simulation/sensors/camera/camera.rst
Labels: build

#706 Update Basilisk Documentation
  docs/source/ExternalSites.rst
  docs/source/Forum.rst
  docs/source/Support/bskReleaseNotes.rst
  docs/source/Vizard/Vizard.rst
  docs/source/_images/static/Basilisk-Logo.pdf
  docs/source/_images/static/Basilisk-Logo.png
  docs/source/_images/static/Basilisk-Logo.svg
  docs/source/_images/static/basiliskVizardLogo.png
  docs/source/index.rst
Labels: documentation
