Repository AVSLab/basilisk, pull requests merged in 2024-10, with the labels that each got.

#828 Update README.md file
  README.md
  docs/source/Support/bskReleaseNotes.rst
Labels: documentation

#829 Add pause function to 2-way scenario
  docs/source/Support/bskReleaseNotes.rst
  docs/source/Vizard/vizardAdvanced/vizardLiveComm.rst
  examples/scenarioBasicOrbitStream.py
  src/utilities/vizSupport.py
Labels: enhancement

#832 Fix RPATH when installing from source for macOS
  docs/source/Install/pipInstall.rst
  docs/source/Support/bskReleaseNotes.rst
  pyproject.toml
  src/CMakeLists.txt
Labels: bug, build

#834 Add SPICE module to scenarioOrbitManeuver scenario
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioOrbitManeuver.py
Labels: enhancement

#825 Enhancement/enhanced polyhedral gravity model
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/gravityEffector/_Documentation/Figures/poly_obj_example.jpg
  src/simulation/dynamics/gravityEffector/_Documentation/Figures/poly_tab_example.jpg
  src/simulation/dynamics/gravityEffector/_Documentation/Figures/poly_txt_example.jpg
  src/simulation/dynamics/gravityEffector/polyhedralGravityModel.cpp
  src/simulation/dynamics/gravityEffector/polyhedralGravityModel.h
  src/simulation/dynamics/gravityEffector/polyhedralGravityModel.rst
Labels: enhancement

#839 Flush vizInterface outputStream buffer when saving to file
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/vizard/vizInterface/vizInterface.cpp
Labels: bug
