Repository AVSLab/basilisk, pull requests merged in 2024-12, with the labels that each got.

#866 Enhance SWIG support for various type arrays
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/_GeneralModuleFiles/swig_conly_data.i
  src/architecture/messaging/_UnitTest/test_CMsgTypes.py
  src/architecture/msgPayloadDefC/TypesTestMsgPayload.h
Labels: enhancement

#868 Fix Windows CI build
  .github/workflows/pull-request.yml
Labels: ci

#865 Refactor/856 refactor facet srp dynamic effector
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioSepMomentumManagement.py
  src/simulation/dynamics/facetSRPDynamicEffector/_UnitTest/test_unitFacetSRPDynamicEffector.py
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.cpp
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.h
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.i
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.rst
Labels: bug, refactor

#870 remove sun sensor gauss markov multiplier
  src/simulation/sensors/coarseSunSensor/_UnitTest/test_coarseSunSensor.py
  src/simulation/sensors/coarseSunSensor/coarseSunSensor.cpp
Labels: bug, refactor

#869 Bug/850 mtbeffector causes issues when interacting with dynmanagersetstate
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/MtbEffector/MtbEffector.i
Labels: bug

#863 Feature/conan2
  .github/workflows/pull-request-closed.yml
  .github/workflows/pull-request.yml
  .gitignore
  conanfile.py
  docs/source/Install/installBuildConan.rst
  docs/source/Install/installOnLinux.rst
  docs/source/Install/installOnMacOS.rst
  docs/source/Install/installOnWindows.rst
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  pyproject.toml
  setup.py
  src/utilities/tests/__init__.py
Labels: enhancement, build

#872 Remove un-needed install code for Linux system
  conanfile.py
Labels: build

#871 Clean up requirements.txt file(s)
  .github/workflows/pull-request-closed.yml
  .github/workflows/pull-request.yml
  conanfile.py
  docs/source/Install.rst
  docs/source/Install/installBuild.rst
  docs/source/Install/installOnLinux.rst
  docs/source/Install/installOnMacOS.rst
  docs/source/Install/installOnWindows.rst
  docs/source/Install/installOptionalPackages.rst
  docs/source/Support/Developer.rst
  docs/source/Support/Developer/CodingGuidlines.rst
  docs/source/Support/Developer/bskModuleCheckoutList.rst
  docs/source/Support/Developer/createHtmlDocumentation.rst
  docs/source/Support/User.rst
  docs/source/Support/User/FAQ.rst
  docs/source/Support/User/FAQwindows.rst
  docs/source/Support/bskReleaseNotes.rst
  examples/MonteCarloExamples/scenarioVisualizeMonteCarlo.py
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  requirements_doc.txt
Labels: documentation, ci, build

#858 Feature/bsk 857 polymorphic state data
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioVariableTimeStepIntegrators.py
  src/simulation/dynamics/FuelTank/fuelTank.i
  src/simulation/dynamics/GravityGradientEffector/GravityGradientEffector.i
  src/simulation/dynamics/HingedRigidBodies/hingedRigidBodyStateEffector.i
  src/simulation/dynamics/LinearSpringMassDamper/linearSpringMassDamper.i
  src/simulation/dynamics/MtbEffector/MtbEffector.i
  src/simulation/dynamics/NHingedRigidBodies/nHingedRigidBodyStateEffector.i
  src/simulation/dynamics/RadiationPressure/radiationPressure.i
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/thrusterDynamicEffector.i
  src/simulation/dynamics/Thrusters/thrusterStateEffector/thrusterStateEffector.i
  src/simulation/dynamics/VSCMGs/vscmgStateEffector.i
  src/simulation/dynamics/_GeneralModuleFiles/dynParamManager.cpp
  src/simulation/dynamics/_GeneralModuleFiles/dynParamManager.h
  src/simulation/dynamics/_GeneralModuleFiles/dynParamManager.i
  src/simulation/dynamics/_GeneralModuleFiles/extendedStateVector.cpp
  src/simulation/dynamics/_GeneralModuleFiles/extendedStateVector.h
  src/simulation/dynamics/_GeneralModuleFiles/stateData.cpp
  src/simulation/dynamics/_GeneralModuleFiles/stateData.h
  src/simulation/dynamics/_GeneralModuleFiles/svIntegratorAdaptiveRungeKutta.h
  src/simulation/dynamics/_GeneralModuleFiles/svIntegratorRungeKutta.h
  src/simulation/dynamics/constraintEffector/constraintDynamicEffector.i
  src/simulation/dynamics/dragEffector/dragDynamicEffector.i
  src/simulation/dynamics/dualHingedRigidBodies/dualHingedRigidBodyStateEffector.i
  src/simulation/dynamics/facetDragEffector/facetDragDynamicEffector.i
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.i
  src/simulation/dynamics/gravityEffector/gravityEffector.i
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesNDOF/linearTranslationNDOFStateEffector.i
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesOneDOF/linearTranslationOneDOFStateEffector.i
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.i
  src/simulation/dynamics/reactionWheels/reactionWheelStateEffector.i
  src/simulation/dynamics/spacecraft/spacecraft.i
  src/simulation/dynamics/spacecraftSystem/spacecraftSystem.i
  src/simulation/dynamics/sphericalPendulum/sphericalPendulum.i
  src/simulation/dynamics/spinningBodies/spinningBodiesNDOF/spinningBodyNDOFStateEffector.i
  src/simulation/dynamics/spinningBodies/spinningBodiesOneDOF/spinningBodyOneDOFStateEffector.i
  src/simulation/dynamics/spinningBodies/spinningBodiesTwoDOF/spinningBodyTwoDOFStateEffector.i
  src/simulation/dynamics/stateArchitecture/_UnitTest/test_stateArchitecture.py
  src/simulation/dynamics/stateArchitecture/stateArchitecture.i
  src/tests/test_scenarioVariableTimeStepIntegrators.py
Labels: enhancement

#882 Latest linux does not directly support Python 3.11
  .github/workflows/pull-request.yml
  docs/source/Support/bskReleaseNotes.rst
Labels: ci, build

#889 Fix Moon equatorial radius value
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/utilities/simIncludeGravBody.py
Labels: bug

#888 Fix subMRP() in RigidBodyKinematics python library
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/utilities/RigidBodyKinematics.py
  src/utilities/tests/test_RigidBodyKinematics.py
Labels: bug

#885 Feature/743 solar array reference fix
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/_UnitTest/test_solarArrayReference.py
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/solarArrayReference.c
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/solarArrayReference.h
  src/fswAlgorithms/effectorInterfaces/solarArrayReference/solarArrayReference.rst
Labels: bug, enhancement

#892 maximumRange not properly considered in groundMapping module
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/environment/groundMapping/_UnitTest/test_groundMapping.py
  src/simulation/environment/groundMapping/groundMapping.cpp
Labels: bug

#891 support matplotlib version 3.10.x
  docs/source/Support/bskReleaseNotes.rst
  examples/BskSim/plotting/BSK_Plotting.py
  examples/scenarioAttGuideHyperbolic.py
  examples/scenarioBasicOrbit.py
  examples/scenarioBasicOrbitStream.py
  examples/scenarioCentralBody.py
  examples/scenarioDragDeorbit.py
  examples/scenarioHaloOrbit.py
  examples/scenarioIntegrators.py
  examples/scenarioLagrangePointOrbit.py
  examples/scenarioOrbitMultiBody.py
  examples/scenarioPatchedConics.py
  requirements.txt
  src/fswAlgorithms/smallBodyNavigation/smallBodyNavEKF/_UnitTest/test_smallBodyNavEKF.py
  src/fswAlgorithms/smallBodyNavigation/smallBodyNavUKF/_UnitTest/test_smallBodyNavUKF.py
  src/simulation/dynamics/DynOutput/orbElemConvert/_UnitTest/test_orb_elem_convert.py
  src/simulation/dynamics/Integrators/_UnitTest/test_Integrators.py
  src/simulation/dynamics/dragEffector/_UnitTest/test_atmoDrag.py
  src/simulation/navigation/planetNav/_UnitTest/test_planetNav.py
  src/simulation/navigation/simpleNav/_UnitTest/test_simpleNav.py
  src/simulation/sensors/coarseSunSensor/_UnitTest/test_coarseSunSensor.py
  src/simulation/sensors/imuSensor/_UnitTest/test_imu_sensor.py
  src/simulation/sensors/simpleVoltEstimator/_UnitTest/test_simpleVoltEstimator.py
  src/tests/test_scenarioIntegrators.py
Labels: bug, documentation
