Repository AVSLab/basilisk, pull requests merged in 2024-09, with the labels that each got.

#785 fix viz settings msg not recording
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/vizard/vizInterface/vizInterface.cpp
Labels: bug

#783 fix rare test_orb_elem_convert.py failures
  src/simulation/dynamics/DynOutput/orbElemConvert/_UnitTest/test_orb_elem_convert.py
Labels: bug

#794 remove deprecated functions
  docs/source/Learn/bskPrinciples.rst
  docs/source/Learn/bskPrinciples/bskPrinciples-10.rst
  docs/source/Learn/bskPrinciples/bskPrinciples-11.rst
  docs/source/Support/bskReleaseNotes.rst
  src/utilities/SimulationBaseClass.py
  src/utilities/tests/test_legacyVariableLogging.py
Labels: documentation, enhancement

#795 Correct math typos in celestialTwoBodyPoint PDF documentation
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/attGuidance/celestialTwoBodyPoint/_Documentation/celestialTwoBodyPoint.pdf
  src/fswAlgorithms/attGuidance/celestialTwoBodyPoint/_Documentation/celestialTwoBodyPoint.tex
Labels: documentation

#786 deprecate classicElements() structure
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioAsteroidArrival.py
  examples/scenarioCustomGravBody.py
  examples/scenarioSmallBodyFeedbackControl.py
  examples/scenarioSmallBodyLandmarks.py
  examples/scenarioSmallBodyNav.py
  examples/scenarioSmallBodyNavUKF.py
  src/architecture/utilities/keplerianOrbit.cpp
  src/architecture/utilities/keplerianOrbit.h
  src/architecture/utilities/keplerianOrbit.i
  src/architecture/utilities/orbitalMotion.c
  src/architecture/utilities/orbitalMotion.h
  src/architecture/utilities/tests/test_orbitalMotion.cpp
  src/fswAlgorithms/attGuidance/velocityPoint/velocityPoint.c
  src/fswAlgorithms/attGuidance/velocityPoint/velocityPoint.h
  src/fswAlgorithms/formationFlying/etSphericalControl/etSphericalControl.c
  src/fswAlgorithms/formationFlying/etSphericalControl/etSphericalControl.h
  src/fswAlgorithms/formationFlying/formationBarycenter/formationBarycenter.cpp
  src/fswAlgorithms/formationFlying/meanOEFeedback/meanOEFeedback.c
  src/fswAlgorithms/formationFlying/meanOEFeedback/meanOEFeedback.h
  src/fswAlgorithms/formationFlying/spacecraftReconfig/spacecraftReconfig.c
  src/fswAlgorithms/formationFlying/spacecraftReconfig/spacecraftReconfig.h
  src/fswAlgorithms/orbitControl/smallBodyWaypointFeedback/_UnitTest/test_smallBodyWaypointFeedback.py
  src/fswAlgorithms/orbitControl/smallBodyWaypointFeedback/smallBodyWaypointFeedback.cpp
  src/fswAlgorithms/orbitControl/smallBodyWaypointFeedback/smallBodyWaypointFeedback.h
  src/fswAlgorithms/smallBodyNavigation/smallBodyNavEKF/smallBodyNavEKF.cpp
  src/fswAlgorithms/smallBodyNavigation/smallBodyNavEKF/smallBodyNavEKF.h
  src/fswAlgorithms/transDetermination/oeStateEphem/oeStateEphem.c
  src/simulation/dynamics/DynOutput/orbElemConvert/orbElemConvert.cpp
  src/simulation/dynamics/DynOutput/orbElemConvert/orbElemConvert.h
  src/simulation/dynamics/gravityEffector/_UnitTest/test_gravitySpacecraft.py
  src/simulation/environment/eclipse/_UnitTest/test_eclipse.py
  src/simulation/environment/planetEphemeris/_UnitTest/test_planetEphemeris.py
  src/simulation/environment/planetEphemeris/_UnitTest/test_planetEphemerisMsgDeprecated.py
  src/simulation/environment/planetEphemeris/planetEphemeris.cpp
  src/simulation/environment/planetEphemeris/planetEphemeris.h
  src/simulation/environment/planetEphemeris/planetEphemeris.i
Labels: enhancement

#792 Expand CI tests to include scenario script testing
  .github/workflows/pull-request.yml
  docs/source/Support/bskReleaseNotes.rst
  src/pytest.ini
  src/tests/test_bskMcTestScript.py
  src/tests/test_bskTestOpNav.py
  src/tests/test_scenarioBasicOrbit.py
Labels: ci

#793 add macOS support to CI tests
  .github/workflows/pull-request.yml
  docs/Makefile
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioBasicOrbitStream.py
Labels: ci

#798 New scenario for Hohmann Transfer with thruster
  docs/source/Support/bskReleaseNotes.rst
  examples/_default.rst
  examples/scenarioOrbitManeuverTH.py
  src/tests/test_scenarioTest.py
Labels: documentation, enhancement

#801 Error on creating message recorders
  docs/source/Support/bskReleaseNotes.rst
  docs/source/index.rst
  src/CMakeLists.txt
  src/architecture/messaging/_UnitTest/test_MessagingInclude.py
  src/moduleTemplates/cModuleTemplate/cModuleTemplate.c
  src/moduleTemplates/cppModuleTemplate/cppModuleTemplate.cpp
Labels: build

#804 Add flag to allow this Action to be run without a PR
  .github/workflows/pull-request-closed.yml
Labels: ci

#803 Add opNav support to Linux and Windows
  .github/workflows/pull-request.yml
  docs/source/Install/installOnLinux.rst
  docs/source/Support/bskReleaseNotes.rst
Labels: ci

#807 Automatically create online documentation
  .github/workflows/pull-request-closed.yml
  docs/source/Support/bskReleaseNotes.rst
Labels: documentation, ci

#809 Misc Fixes
  .github/workflows/pull-request-closed.yml
  examples/scenarioFormationBasic.py
  src/fswAlgorithms/attDetermination/sunlineSEKF/sunlineSEKF.c
  src/fswAlgorithms/smallBodyNavigation/smallBodyNavUKF/smallBodyNavUKF.cpp
  src/simulation/dynamics/facetSRPDynamicEffector/facetSRPDynamicEffector.cpp
  src/simulation/environment/albedo/albedo.cpp
  src/simulation/environment/spiceInterface/spiceInterface.cpp
  src/simulation/onboardDataHandling/storageUnit/partitionedStorageUnit.cpp
Labels: ci

#805 Sweeping satellite Earth Imaging scenario
  docs/source/Support/bskReleaseNotes.rst
  examples/_default.rst
  examples/scenarioSweepingSpacecraft.py
  src/tests/test_scenarioSweepingSpacecraft.py
Labels: enhancement

#810 fix xcode 16 compiler warning
  src/simulation/environment/albedo/albedo.cpp
Labels: build

#816 simIncludeRW didn't allow specify certain RW friction parameters
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/reactionWheels/_UnitTest/test_reactionWheelStateEffector_integrated.py
  src/utilities/simIncludeRW.py
Labels: bug

#815 Add latest linux OS to CI build
  .github/workflows/pull-request.yml
  docs/source/Support/bskReleaseNotes.rst
Labels: ci

#813 N-axis Translating Effector
  docs/source/Support/bskReleaseNotes.rst
  examples/_default.rst
  examples/scenarioExtendingBoom.py
  src/simulation/deviceInterface/prescribedLinearTranslation/prescribedLinearTranslation.cpp
  src/simulation/deviceInterface/prescribedLinearTranslation/prescribedLinearTranslation.h
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesNDOF/_UnitTest/test_linearTranslationNDOFStateEffector.py
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesNDOF/linearTranslationNDOFStateEffector.cpp
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesNDOF/linearTranslationNDOFStateEffector.h
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesNDOF/linearTranslationNDOFStateEffector.i
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesNDOF/linearTranslationNDOFStateEffector.rst
  src/tests/test_scenarioTest.py
Labels: enhancement

#820 Small build maintenance steps
  docs/source/Support/bskReleaseNotes.rst
  src/CMakeLists.txt
  src/architecture/utilities/CMakeLists.txt
  src/utilities/CMakeLists.txt
  src/utilities/overwriteSwig.py
  src/utilities/vizProtobuffer/CMakeLists.txt
Labels: build

#823 BSK release v2.5.0
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskVersion.txt
Labels: documentation

#824 Next BSK beta cycle
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
Labels: documentation
