Repository AVSLab/basilisk, pull requests merged in 2024-11, with the labels that each got.

#818 Refactor pyswice utilities
  docs/source/Support/bskReleaseNotes.rst
  src/utilities/pyswice_ck_utilities.py
  src/utilities/pyswice_spk_utilities.py
  src/utilities/tests/test_ck_utilities.py
  supportData/EphemerisData/MVN_SCLKSCET.00000.tsc
Labels: documentation, refactor

#841 Updates to BSK Documentation System
  docs/source/Install/installOptionalPackages.rst
  docs/source/Support/bskReleaseNotes.rst
  docs/source/conf.py
  examples/BskSim/scenarios/scenario_AttGuidHyperbolic.py
  examples/BskSim/scenarios/scenario_AttGuidance.py
  examples/BskSim/scenarios/scenario_AttSteering.py
  examples/BskSim/scenarios/scenario_FeedbackRW.py
  examples/BskSim/scenarios/scenario_LambertGuidance.py
  examples/OpNavScenarios/modelsOpNav/BSK_OpNavDynamics.py
  examples/_default.rst
  requirements_optional.txt
Labels: documentation

#835 Feature/bokeh mc bringup
  docs/source/Support/bskReleaseNotes.rst
  docs/source/conf.py
  examples/BskSim/scenarios/scenario_AttFeedback.py
  examples/MonteCarloExamples/scenarioAnalyzeMonteCarlo.py
  examples/MonteCarloExamples/scenarioBskSimAttFeedbackMC.py
  examples/MonteCarloExamples/scenarioRerunMonteCarlo.py
  examples/MonteCarloExamples/scenarioVisualizeMonteCarlo.py
  examples/_default.rst
  examples/scenarioMonteCarloAttRW.py
  examples/scenarioMonteCarloSpice.py
  requirements_optional.txt
  src/tests/test_bskMcTestScript.py
  src/tests/test_scenarioMonteCarloAttRW.py
  src/tests/test_scenarioMonteCarloSpice.py
  src/utilities/MonteCarlo/AnalysisBaseClass.py
  src/utilities/MonteCarlo/DataWriter.py
  src/utilities/MonteCarlo/RetentionPolicy.py
  src/utilities/datashader_utilities.py
Labels: documentation, enhancement

#843 vizInterface unit test
  .gitignore
  conanfile.py
  docs/source/Support/bskReleaseNotes.rst
  requirements_optional.txt
  src/simulation/vizard/vizInterface/_UnitTest/test_vizInterface.py
  src/utilities/vizProtobuffer/CMakeLists.txt
  src/utilities/vizProtobuffer/vizMessage.proto
Labels: enhancement

#842 Update scenarios to include YouTube videos
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioFlexiblePanel.py
  examples/scenarioRoboticArm.py
  examples/scenarioRotatingPanel.py
Labels: documentation

#845 fix: (hack) Ensure vizinterface knows about RWModels enum.
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/vizard/vizInterface/vizInterface.i
Labels: bug
