Repository AVSLab/basilisk, pull requests merged in 2024-04, with the labels that each got.

#655 Updated release notes about Updating online documentation
  docs/source/Support/bskReleaseNotes.rst
Labels: documentation

#653 Feature/bsk 612 smooth rotational profiler
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioDeployingSolarArrays.py
  src/simulation/deviceInterface/prescribedRotation1DOF/_UnitTest/test_prescribedRotation1DOF.py
  src/simulation/deviceInterface/prescribedRotation1DOF/prescribedRotation1DOF.cpp
  src/simulation/deviceInterface/prescribedRotation1DOF/prescribedRotation1DOF.h
  src/simulation/deviceInterface/prescribedRotation1DOF/prescribedRotation1DOF.rst
Labels: enhancement

#657 Refactor/bsk 656 tweak prescribed linear translation
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/deviceInterface/prescribedLinearTranslation/prescribedLinearTranslation.cpp
  src/simulation/deviceInterface/prescribedLinearTranslation/prescribedLinearTranslation.h
Labels: refactor

#661 Feature/bsk 2 3 0
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskVersion.txt
Labels: documentation

#662 Prepare for next beta cycle
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
Labels: documentation

#664 Remove defunct manner of creating a BSK python module
  docs/source/Learn/makingModules/pyModules.rst
  docs/source/Support/bskReleaseNotes.rst
  examples/_default.rst
  examples/scenarioAttitudePointingPy.py
  examples/scenarioAttitudePointingPyDEPRECATED.py
  src/tests/test_scenarioAttitudePointingPyDEPRECATED.py
  src/utilities/SimulationBaseClass.py
  src/utilities/simulationArchTypes.py
Labels: documentation, build

#672 Feature/658 Print exceptions raised in Python modules
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/_GeneralModuleFiles/py_sys_model.i
  src/architecture/system_model/_UnitTest/test_PySysModel.py
Labels: enhancement
