Repository AVSLab/basilisk, pull requests merged in 2024-06, with the labels that each got.

#707 add support for pre-commit and clang-format format checking
  .clang-format
  .pre-commit-config.yaml
  CONTRIBUTING.md
  docs/source/Install/installOptionalPackages.rst
  docs/source/Support/Developer/CodingGuidlines.rst
  docs/source/Support/bskReleaseNotes.rst
  requirements_optional.txt
Labels: documentation, enhancement, build

#708 update CI scripts
  .github/workflows/pull-request.yml
  CONTRIBUTING.md
Labels: build

#677 N-Axis Effector Scenarios
  docs/source/Support/bskReleaseNotes.rst
  examples/_default.rst
  examples/scenarioFlexiblePanel.py
  examples/scenarioRoboticArm.py
  src/tests/test_scenarioFlexiblePanel.py
  src/tests/test_scenarioTest.py
Labels: enhancement

#713 fix protect all classes
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/_GeneralModuleFiles/swig_conly_data.i
  src/fswAlgorithms/stateEstimation/thrustCMEstimation/thrustCMEstimation.i
  src/simulation/dynamics/spinningBodies/spinningBodiesNDOF/spinningBodyNDOFStateEffector.i
  src/simulation/navigation/pinholeCamera/pinholeCamera.i
  src/tests/test_protectAllClasses.py
Labels: bug

#716 Update instructions for C++ BSK modules to use setters and getters
  docs/source/Learn/bskPrinciples/bskPrinciples-6.rst
  docs/source/Learn/makingModules/cppModules/cppModules-1.rst
  docs/source/Learn/makingModules/cppModules/cppModules-3.rst
  docs/source/Support/bskReleaseNotes.rst
  docs/source/codeSamples/bsk-6.py
  src/architecture/_GeneralModuleFiles/swig_std_array.i
  src/architecture/_GeneralModuleFiles/sys_model.i
  src/moduleTemplates/cppModuleTemplate/_UnitTest/test_cppModuleTemplateParametrized.py
  src/moduleTemplates/cppModuleTemplate/cppModuleTemplate.cpp
  src/moduleTemplates/cppModuleTemplate/cppModuleTemplate.h
  src/utilities/makeDraftModule.py
Labels: documentation, enhancement

#719 Feature/add interpolation functions
  docs/source/conf.py
  src/architecture/utilities/bilinearInterpolation.hpp
  src/architecture/utilities/linearInterpolation.hpp
  src/architecture/utilities/tests/CMakeLists.txt
  src/architecture/utilities/tests/test_bilinearInterpolation.cpp
  src/architecture/utilities/tests/test_linearInterpolation.cpp
Labels: enhancement

#727 Feature/726 Support Numpy 2.0
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/attGuidance/waypointReference/_UnitTest/test_WaypointReference.py
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_UnitTest/test_ThrusterDynamicsUnit.py
  src/utilities/fswSetupRW.py
  src/utilities/orbitalMotion.py
  src/utilities/readAtmTable.py
Labels: enhancement

#717 Use spherical/geocentric coordinates correctly in WMM
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/environment/magneticFieldWMM/_UnitTest/test_magneticFieldWMM.py
  src/simulation/environment/magneticFieldWMM/magneticFieldWMM.cpp
  src/simulation/environment/magneticFieldWMM/magneticFieldWMM.h
Labels: bug

#678 Feature/constraintEffector
  docs/source/Support/bskReleaseNotes.rst
  examples/_default.rst
  examples/scenarioConstrainedDynamics.py
  src/simulation/dynamics/constraintEffector/_UnitTest/test_ConstraintDynamicEffectorUnit.py
  src/simulation/dynamics/constraintEffector/constraintDynamicEffector.cpp
  src/simulation/dynamics/constraintEffector/constraintDynamicEffector.h
  src/simulation/dynamics/constraintEffector/constraintDynamicEffector.i
  src/simulation/dynamics/constraintEffector/constraintDynamicEffector.rst
  src/tests/test_scenarioConstrainedDynamics.py
Labels: enhancement
