Repository AVSLab/basilisk, pull requests merged in 2025-08, with the labels that each got.

#1044 Feature/bsk-1043: Active set allocation and bug fix in forceTorqueThrForceMapping
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  requirements_doc.txt
  src/fswAlgorithms/effectorInterfaces/forceTorqueThrForceMapping/_UnitTest/test_forceTorqueThrForceMapping.py
  src/fswAlgorithms/effectorInterfaces/forceTorqueThrForceMapping/forceTorqueThrForceMapping.c
Labels: bug

#1059 Add ability to specify vizInterface data file name and path
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/vizard/vizInterface/vizInterface.cpp
  src/utilities/vizSupport.py
Labels: enhancement

#1066 Convert RW raw pointers to smart pointers
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/_GeneralModuleFiles/RWConfigPayload.h
  src/simulation/dynamics/_GeneralModuleFiles/RWConfigPayload.i
  src/simulation/dynamics/reactionWheels/_UnitTest/test_reactionWheelStateEffector_ConfigureRWRequests.py
  src/simulation/dynamics/reactionWheels/reactionWheelStateEffector.cpp
  src/simulation/dynamics/reactionWheels/reactionWheelStateEffector.h
  src/simulation/dynamics/reactionWheels/reactionWheelStateEffector.i
  src/simulation/thermal/motorThermal/_UnitTest/test_motorThermal.py
  src/utilities/makeDraftModule.py
  src/utilities/simIncludeRW.py
Labels: refactor

#1078 Implement VSCMG Velocity Steering module
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/effectorInterfaces/vscmgVelocitySteering/_UnitTest/test_vscmgVelocitySteering.py
  src/fswAlgorithms/effectorInterfaces/vscmgVelocitySteering/vscmgVelocitySteering.cpp
  src/fswAlgorithms/effectorInterfaces/vscmgVelocitySteering/vscmgVelocitySteering.h
  src/fswAlgorithms/effectorInterfaces/vscmgVelocitySteering/vscmgVelocitySteering.i
  src/fswAlgorithms/effectorInterfaces/vscmgVelocitySteering/vscmgVelocitySteering.rst
Labels: documentation, enhancement

#1082 Basilisk v.2.8.0 release
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskVersion.txt
Labels: documentation

#1083 update release notes and known issues documents
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
Labels: documentation
