Repository AVSLab/basilisk, pull requests merged in 2025-04, with the labels that each got.

#959 Add Locations using lat/lon/alt
  docs/source/Support/bskReleaseNotes.rst
  docs/source/Vizard/vizardAdvanced/vizardSettings.rst
  examples/scenarioGroundLocationImaging.py
  src/utilities/vizSupport.py
Labels: enhancement

#943 Feature/817 mechanism for zeroing effector control alg msg outputs
  docs/source/Support/bskReleaseNotes.rst
  examples/MultiSatBskSim/modelsMultiSat/BSK_MultiSatFsw.py
  src/architecture/messaging/messaging.h
  src/fswAlgorithms/effectorInterfaces/dipoleMapping/_UnitTest/test_dipoleMapping.py
  src/fswAlgorithms/effectorInterfaces/dipoleMapping/dipoleMapping.c
  src/fswAlgorithms/effectorInterfaces/dipoleMapping/dipoleMapping.h
  src/fswAlgorithms/effectorInterfaces/dipoleMapping/dipoleMapping.rst
  src/fswAlgorithms/effectorInterfaces/forceTorqueThrForceMapping/_UnitTest/test_forceTorqueThrForceMapping.py
  src/fswAlgorithms/effectorInterfaces/forceTorqueThrForceMapping/forceTorqueThrForceMapping.c
  src/fswAlgorithms/effectorInterfaces/forceTorqueThrForceMapping/forceTorqueThrForceMapping.rst
  src/fswAlgorithms/effectorInterfaces/rwMotorVoltage/_UnitTest/test_rwMotorVoltage.py
  src/fswAlgorithms/effectorInterfaces/rwMotorVoltage/rwMotorVoltage.c
  src/fswAlgorithms/effectorInterfaces/rwMotorVoltage/rwMotorVoltage.rst
  src/fswAlgorithms/effectorInterfaces/thrFiringRemainder/_UnitTest/test_thrFiringRemainder.py
  src/fswAlgorithms/effectorInterfaces/thrFiringRemainder/thrFiringRemainder.c
  src/fswAlgorithms/effectorInterfaces/thrFiringRemainder/thrFiringRemainder.rst
  src/fswAlgorithms/effectorInterfaces/thrFiringSchmitt/_UnitTest/test_thrFiringSchmitt.py
  src/fswAlgorithms/effectorInterfaces/thrFiringSchmitt/thrFiringSchmitt.c
  src/fswAlgorithms/effectorInterfaces/thrFiringSchmitt/thrFiringSchmitt.rst
  src/fswAlgorithms/effectorInterfaces/thrustRWDesat/_UnitTest/test_thrustRWDesat.py
  src/fswAlgorithms/effectorInterfaces/thrustRWDesat/thrustRWDesat.c
  src/fswAlgorithms/effectorInterfaces/thrustRWDesat/thrustRWDesat.rst
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/thrusterPlatformReference.c
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/thrusterPlatformReference.rst
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformState/_UnitTest/test_thrusterPlatformState.py
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformState/thrusterPlatformState.c
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformState/thrusterPlatformState.rst
  src/fswAlgorithms/effectorInterfaces/torque2Dipole/_UnitTest/test_torque2Dipole.py
  src/fswAlgorithms/effectorInterfaces/torque2Dipole/torque2Dipole.c
  src/fswAlgorithms/effectorInterfaces/torque2Dipole/torque2Dipole.rst
  src/fswAlgorithms/effectorInterfaces/torqueScheduler/_UnitTest/test_torqueScheduler.py
  src/fswAlgorithms/effectorInterfaces/torqueScheduler/torqueScheduler.c
  src/fswAlgorithms/effectorInterfaces/torqueScheduler/torqueScheduler.rst
Labels: enhancement

#975 Refactor/974 refactor prescribed motion body frame
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioDeployingSolarArrays.py
  src/architecture/msgPayloadDefC/PrescribedMotionMsgPayload.h
  src/architecture/msgPayloadDefC/PrescribedRotationMsgPayload.h
  src/architecture/msgPayloadDefC/PrescribedTranslationMsgPayload.h
  src/fswAlgorithms/effectorInterfaces/prescribedRot1DOF/_UnitTest/test_prescribedRot1DOF.py
  src/fswAlgorithms/effectorInterfaces/prescribedRot1DOF/prescribedRot1DOF.c
  src/fswAlgorithms/effectorInterfaces/prescribedRot1DOF/prescribedRot1DOF.h
  src/fswAlgorithms/effectorInterfaces/prescribedRot1DOF/prescribedRot1DOF.i
  src/fswAlgorithms/effectorInterfaces/prescribedRot1DOF/prescribedRot1DOF.rst
  src/fswAlgorithms/effectorInterfaces/prescribedRot2DOF/_UnitTest/test_prescribedRot2DOF.py
  src/fswAlgorithms/effectorInterfaces/prescribedRot2DOF/prescribedRot2DOF.c
  src/fswAlgorithms/effectorInterfaces/prescribedRot2DOF/prescribedRot2DOF.h
  src/fswAlgorithms/effectorInterfaces/prescribedRot2DOF/prescribedRot2DOF.rst
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/_UnitTest/test_prescribedTrans.py
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/prescribedTrans.c
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/prescribedTrans.h
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/prescribedTrans.i
  src/fswAlgorithms/effectorInterfaces/prescribedTrans/prescribedTrans.rst
  src/simulation/deviceInterface/prescribedLinearTranslation/_UnitTest/test_prescribedLinearTranslation.py
  src/simulation/deviceInterface/prescribedLinearTranslation/prescribedLinearTranslation.cpp
  src/simulation/deviceInterface/prescribedLinearTranslation/prescribedLinearTranslation.h
  src/simulation/deviceInterface/prescribedLinearTranslation/prescribedLinearTranslation.rst
  src/simulation/deviceInterface/prescribedRotation1DOF/_UnitTest/test_prescribedRotation1DOF.py
  src/simulation/deviceInterface/prescribedRotation1DOF/prescribedRotation1DOF.cpp
  src/simulation/deviceInterface/prescribedRotation1DOF/prescribedRotation1DOF.h
  src/simulation/deviceInterface/prescribedRotation1DOF/prescribedRotation1DOF.rst
  src/simulation/dynamics/prescribedMotion/_UnitTest/test_PrescribedMotionStateEffector.py
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.cpp
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.h
  src/simulation/dynamics/prescribedMotion/prescribedMotionStateEffector.rst
Labels: enhancement, refactor

#980 Feature/979 mujoco stateful sysmodel
  docs/source/Support/bskReleaseNotes.rst
  examples/mujoco/scenarioDeployPanels.py
  src/architecture/_GeneralModuleFiles/py_sys_model.i
  src/simulation/mujocoDynamics/_GeneralModuleFiles/MJBody.cpp
  src/simulation/mujocoDynamics/_GeneralModuleFiles/MJBody.h
  src/simulation/mujocoDynamics/_GeneralModuleFiles/MJScene.cpp
  src/simulation/mujocoDynamics/_GeneralModuleFiles/StatefulSysModel.h
  src/simulation/mujocoDynamics/_GeneralModuleFiles/_UnitTest/test_stateful_sys_model.py
  src/simulation/mujocoDynamics/_GeneralModuleFiles/pyStatefulSysModel.i
Labels: enhancement

#985 Online documentation was not building
  .github/workflows/pull-request-closed.yml
  .github/workflows/pull-request.yml
Labels: bug, documentation, ci

#967 Change thrusterData to a pointer
  docs/source/Support/bskReleaseNotes.rst
  examples/BskSim/models/BSK_Dynamics.py
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/_UnitTest/test_ThrusterDynamicsUnit.py
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/thrusterDynamicEffector.cpp
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/thrusterDynamicEffector.h
  src/simulation/dynamics/Thrusters/thrusterDynamicEffector/thrusterDynamicEffector.i
  src/simulation/dynamics/Thrusters/thrusterStateEffector/thrusterStateEffector.cpp
  src/simulation/dynamics/Thrusters/thrusterStateEffector/thrusterStateEffector.h
  src/simulation/dynamics/Thrusters/thrusterStateEffector/thrusterStateEffector.i
  src/simulation/dynamics/_GeneralModuleFiles/THRSimConfig.h
  src/simulation/dynamics/_GeneralModuleFiles/THRSimConfig.i
Labels: enhancement

#986 BSK 2.7.0 release
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskVersion.txt
Labels: documentation

#987 Next beta cycle after 2.7.0
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
Labels: documentation

#989 Hotfix/Compiler Warnings MuJocO
  src/CMakeLists.txt
  src/simulation/mujocoDynamics/_GeneralModuleFiles/MJQPosStateData.h
  src/simulation/mujocoDynamics/_GeneralModuleFiles/MJScene.h
  src/simulation/mujocoDynamics/_GeneralModuleFiles/MJSite.cpp
  src/simulation/mujocoDynamics/_GeneralModuleFiles/MJUtils.h
Labels: build

#988 Deprecate Python 3.8
  docs/source/Install/installOnLinux.rst
  docs/source/Install/installOnMacOS.rst
  docs/source/Install/installOnWindows.rst
  docs/source/Support/bskReleaseNotes.rst
  src/CMakeLists.txt
Labels: documentation, build

#991 Remove opNavMode
  docs/source/Support/bskReleaseNotes.rst
  docs/source/Vizard/vizardAdvanced/vizardLiveComm.rst
  examples/OpNavScenarios/scenariosOpNav/OpNavMC/scenario_LimbAttOD.py
  examples/OpNavScenarios/scenariosOpNav/OpNavMC/scenario_OpNavAttODMC.py
  src/simulation/vizard/vizInterface/vizInterface.cpp
  src/simulation/vizard/vizInterface/vizInterface.h
  src/simulation/vizard/vizInterface/vizInterface.i
  src/utilities/vizSupport.py
Labels: refactor

#992 Add QuadMap demo video
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioQuadMaps.py
Labels: documentation

#984 Pin python dependencies
  .github/workflows/canary.yml
  .github/workflows/requirements.txt
  .github/workflows/requirements_dev.txt
  .github/workflows/requirements_doc.txt
  conanfile.py
  docs/source/Support/bskReleaseNotes.rst
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  requirements_doc.txt
Labels: enhancement
