Repository AVSLab/basilisk, pull requests merged in 2025-03, with the labels that each got.

#945 Bug/272 reaction wheel no max torque ends sim no error
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/dynamics/reactionWheels/reactionWheelStateEffector.cpp
  src/simulation/dynamics/reactionWheels/reactionWheelStateEffector.h
  src/simulation/dynamics/reactionWheels/reactionWheelStateEffector.rst
Labels: bug

#947 [#946] Fix calculation in spacecraftLocation
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/environment/spacecraftLocation/spacecraftLocation.cpp
Labels: bug

#949 Vizard 2.2.2 Support
  docs/source/Support/Developer/deprecatingCode.rst
  docs/source/Support/bskReleaseNotes.rst
  docs/source/Vizard/VizardReleaseNotes.rst
  docs/source/Vizard/vizardAdvanced/vizardSettings.rst
  examples/scenarioCustomGravBody.py
  examples/scenarioDataToViz.py
  examples/scenarioDebrisReorbitET.py
  examples/scenarioDeployingSolarArrays.py
  examples/scenarioSepMomentumManagement.py
  src/architecture/_GeneralModuleFiles/swig_deprecated.i
  src/simulation/vizard/_GeneralModuleFiles/vizStructures.h
  src/simulation/vizard/vizInterface/vizInterface.cpp
  src/simulation/vizard/vizInterface/vizInterface.i
  src/utilities/vizProtobuffer/vizMessage.proto
  src/utilities/vizSupport.py
Labels: documentation, enhancement

#954 Bug/rerun monte carlo patch
  docs/source/Support/bskReleaseNotes.rst
  examples/MonteCarloExamples/scenarioRerunMonteCarlo.py
Labels: bug

#956 Feature/bug thruster platform reference
  docs/source/Support/bskReleaseNotes.rst
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/_UnitTest/test_thrusterPlatformReference.py
  src/fswAlgorithms/effectorInterfaces/thrusterPlatformReference/thrusterPlatformReference.c
Labels: bug

#918 Bug/819 memory leak fixes
  .github/workflows/pull-request.yml
  docs/source/Learn/bskPrinciples/bskPrinciples-5.rst
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  examples/BskSim/models/BSK_Dynamics.py
  examples/MultiSatBskSim/scenariosMultiSat/scenario_BasicOrbitMultiSat.py
  examples/MultiSatBskSim/scenariosMultiSat/scenario_BasicOrbitMultiSat_MT.py
  examples/MultiSatBskSim/scenariosMultiSat/scenario_StationKeepingMultiSat.py
  examples/OpNavScenarios/modelsOpNav/BSK_OpNavDynamics.py
  examples/scenarioCSSFilters.py
  examples/scenarioExtendingBoom.py
  examples/scenarioFlexiblePanel.py
  examples/scenarioMonteCarloAttRW.py
  examples/scenarioRoboticArm.py
  examples/scenarioSepMomentumManagement.py
  requirements_dev.txt
  src/architecture/_GeneralModuleFiles/swig_eigen.i
  src/simulation/dynamics/reactionWheels/_UnitTest/test_reactionWheelMemoryLeak.py
  src/simulation/dynamics/reactionWheels/reactionWheelStateEffector.cpp
  src/simulation/dynamics/reactionWheels/reactionWheelStateEffector.i
  src/simulation/sensors/coarseSunSensor/coarseSunSensor.rst
  src/utilities/fswSetupRW.py
  src/utilities/fswSetupThrusters.py
  src/utilities/simIncludeRW.py
  src/utilities/simIncludeThruster.py
  src/utilities/unitTestSupport.py
  src/utilities/vizSupport.py
Labels: bug

#961 Enhancement/96 add unit tests for avs eigen support
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/utilities/tests/CMakeLists.txt
  src/architecture/utilities/tests/test_avsEigenSupport.cpp
Labels: enhancement, good first issue

#948 Add support for Python 3.13
  .github/workflows/pull-request.yml
  docs/source/Install/installOnLinux.rst
  docs/source/Install/installOnMacOS.rst
  docs/source/Install/installOnWindows.rst
  docs/source/Support/bskReleaseNotes.rst
  examples/MonteCarloExamples/scenarioRerunMonteCarlo.py
  pyproject.toml
  src/architecture/_GeneralModuleFiles/swig_conly_data.i
  src/fswAlgorithms/attControl/mtbMomentumManagementSimple/mtbMomentumManagementSimple.c
  src/fswAlgorithms/attDetermination/sunlineUKF/_UnitTest/test_SunLineUKF.py
  src/fswAlgorithms/attGuidance/eulerRotation/_UnitTest/test_eulerRotation.py
  src/fswAlgorithms/attGuidance/inertial3DSpin/_UnitTest/test_inertial3DSpin.py
  src/fswAlgorithms/effectorInterfaces/dipoleMapping/dipoleMapping.c
  src/fswAlgorithms/transDetermination/chebyPosEphem/_UnitTest/test_chebyPosEphem.py
  src/simulation/dynamics/HingedRigidBodies/_UnitTest/test_hingedRigidBodyStateEffector.py
  src/simulation/dynamics/Integrators/_UnitTest/test_Integrators.py
  src/simulation/dynamics/constraintEffector/_UnitTest/test_ConstraintDynamicEffectorUnit.py
  src/simulation/dynamics/extForceTorque/_UnitTest/test_extForceTorqueIntegrated.py
  src/simulation/dynamics/gravityEffector/_UnitTest/test_gravitySpacecraft.py
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesNDOF/_UnitTest/test_linearTranslationNDOFStateEffector.py
  src/simulation/dynamics/linearTranslationalBodies/linearTranslationBodiesOneDOF/_UnitTest/test_linearTranslationOneDOFStateEffector.py
  src/simulation/dynamics/spacecraft/_UnitTest/test_spacecraft.py
  src/simulation/dynamics/spacecraftSystem/_UnitTest/test_multiSpacecraft.py
  src/simulation/dynamics/spinningBodies/spinningBodiesNDOF/_UnitTest/test_spinningBodyNDOFStateEffector.py
  src/simulation/onboardDataHandling/instrument/simpleInstrument/_UnitTest/test_simpleInstrument.py
  src/simulation/onboardDataHandling/transmitter/_UnitTest/test_simpleTransmitter.py
  src/simulation/power/simplePowerSink/_UnitTest/test_unitSimplePowerSink.py
  src/tests/test_messaging.py
  src/tests/test_utilitiesUKF.py
  src/utilities/MonteCarlo/Controller.py
  src/utilities/MonteCarlo/Dispersions.py
  src/utilities/SimulationBaseClass.py
  src/utilities/datasheet_RW.py
  src/utilities/simIncludeRW.py
  src/utilities/simIncludeThruster.py
Labels: documentation, enhancement, ci
