Repository AVSLab/basilisk, pull requests merged in 2025-02, with the labels that each got.

#922 Windows was not running opNav and vizInterface with conan2
  .github/workflows/pull-request.yml
  conanfile.py
  docs/source/Support/bskReleaseNotes.rst
  src/conftest.py
Labels: ci, build

#879 Feature/877 add battery capacity fault capability
  docs/source/Support/bskReleaseNotes.rst
  src/architecture/msgPayloadDefC/PowerStorageFaultMsgPayload.h
  src/simulation/power/simpleBattery/_UnitTest/test_simpleBatteryFault.py
  src/simulation/power/simpleBattery/simpleBattery.cpp
  src/simulation/power/simpleBattery/simpleBattery.h
  src/simulation/power/simpleBattery/simpleBattery.i
  src/simulation/power/simpleBattery/simpleBattery.rst
Labels: enhancement

#931 Add --mujoco and --mujocoReplay options to conanfile.py
  conanfile.py
Labels: build

#935 Clarify when an issue is closed
  CONTRIBUTING.md
Labels: documentation

#938 Basilisk v2.6.0
  docs/source/Support/bskReleaseNotes.rst
  docs/source/bskVersion.txt
Labels: documentation

#939 Update for next BSK beta cycle
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
Labels: documentation

#936 Edit pull-request.yml to run mujoco tests in some jobs
  .github/workflows/pull-request.yml
  docs/source/Support/bskReleaseNotes.rst
Labels: build

#940 Misc CI and documentation updates
  .github/workflows/pull-request.yml
  docs/source/Support/bskReleaseNotes.rst
  docs/source/index.rst
Labels: documentation, ci

#944 Enhancement/172 update make draft module
  docs/source/Support/bskReleaseNotes.rst
  src/utilities/makeDraftModule.py
Labels: enhancement, good first issue
