Repository AVSLab/basilisk, pull requests merged in 2025-01, with the labels that each got.

#896 JPL NAIF servers are down
  src/CMakeLists.txt
  src/utilities/bskLargeData.py
Labels: build

#895 Feature/750 scenario sep momentum management updates
  examples/scenarioSepMomentumManagement.py
  src/tests/test_scenarioSepMomentumManagement.py
Labels: enhancement

#898 Feature/750 scenario sep momentum management release notes
  docs/source/Support/bskReleaseNotes.rst
Labels: documentation

#900 JPL NAIF servers back online
  src/CMakeLists.txt
  src/utilities/bskLargeData.py
Labels: build

#899 Add support for Python 3.12
  .github/workflows/pull-request.yml
  docs/source/Install/installOnLinux.rst
  docs/source/Install/installOnMacOS.rst
  docs/source/Install/installOnWindows.rst
  docs/source/Support/bskReleaseNotes.rst
  pyproject.toml
  src/architecture/_GeneralModuleFiles/py_sys_model.i
  src/architecture/messaging/msgAutoSource/msgInterfacePy.i.in
  src/architecture/system_model/sim_model.i
  src/architecture/system_model/sys_model_task.i
Labels: bug

#881 Refactor GaussMarkov sensor noise handling
  docs/source/Support/bskKnownIssues.rst
  docs/source/Support/bskReleaseNotes.rst
  examples/scenarioGaussMarkovRandomWalk.py
  src/simulation/sensors/coarseSunSensor/coarseSunSensor.cpp
  src/simulation/sensors/coarseSunSensor/coarseSunSensor.h
  src/simulation/sensors/imuSensor/_UnitTest/test_imu_sensor.py
  src/simulation/sensors/imuSensor/imuSensor.cpp
  src/simulation/sensors/imuSensor/imuSensor.h
  src/simulation/sensors/magnetometer/magnetometer.cpp
  src/simulation/sensors/magnetometer/magnetometer.h
  src/simulation/sensors/simpleVoltEstimator/simpleVoltEstimator.cpp
  src/simulation/sensors/simpleVoltEstimator/simpleVoltEstimator.h
  src/simulation/sensors/starTracker/starTracker.cpp
  src/simulation/sensors/starTracker/starTracker.h
Labels: documentation, enhancement

#904 Enhance documentation on making new message for a module
  docs/source/Learn/makingModules/makingModules-2.rst
  docs/source/Support/bskReleaseNotes.rst
Labels: documentation

#894 Vizard 2.2.1 Support
  conanfile.py
  docs/source/Support/bskReleaseNotes.rst
  docs/source/Vizard/Vizard.rst
  docs/source/Vizard/VizardDownload.rst
  docs/source/Vizard/VizardGUI.rst
  docs/source/Vizard/VizardReleaseNotes.rst
  docs/source/Vizard/assetIceSat2_Kepler.rst
  docs/source/Vizard/vizardAdvanced/vizardLiveComm.rst
  docs/source/Vizard/vizardAdvanced/vizardSettings.rst
  docs/source/_images/static/vizard-HotKey.jpg
  docs/source/_images/static/vizard-Img2.jpg
  docs/source/_images/static/vizard-ImgCAD-1.jpg
  docs/source/_images/static/vizard-ImgCAD-6.jpg
  docs/source/_images/static/vizard-ImgPointing.jpg
  docs/source/_images/static/vizard-Labels.jpg
  docs/source/_images/static/vizard-bodyInertialFrame.jpg
  docs/source/_images/static/vizard-fixedFrame.jpg
  docs/source/_images/static/vizard-rotatingFrame.jpg
  docs/source/_images/static/vizard-scRelative.jpg
  examples/scenarioAsteroidArrival.py
  examples/scenarioDataToViz.py
  examples/scenarioHaloOrbit.py
  examples/scenarioOrbitManeuver.py
  requirements.txt
  src/simulation/sensors/coarseSunSensor/_UnitTest/test_coarseSunSensor.py
  src/simulation/vizard/_GeneralModuleFiles/vizStructures.h
  src/simulation/vizard/vizInterface/vizInterface.cpp
  src/simulation/vizard/vizInterface/vizInterface.rst
  src/utilities/vizProtobuffer/CMakeLists.txt
  src/utilities/vizProtobuffer/vizMessage.proto
Labels: documentation, enhancement
