Repository AVSLab/basilisk, pull requests merged in 2025-09, with the labels that each got.

#1090 Remove deprecated use of basilisk.simulation.planet ephemeris.classic elements msg payload
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/environment/planetEphemeris/_UnitTest/test_planetEphemerisMsgDeprecated.py
  src/simulation/environment/planetEphemeris/planetEphemeris.i
Labels: enhancement

#1098 Build docs from bumped version commit
  .github/workflows/merge.yml
Labels: documentation, ci

#1096 add magnetometer faulting capability
  docs/source/Support/bskReleaseNotes.rst
  src/simulation/sensors/magnetometer/_UnitTest/test_magnetometerFaults.py
  src/simulation/sensors/magnetometer/magnetometer.cpp
  src/simulation/sensors/magnetometer/magnetometer.h
  src/simulation/sensors/magnetometer/magnetometer.rst
Labels: enhancement

#1101 Refactor/Update MJSystemCOM EOM Call
  src/simulation/mujocoDynamics/MJSystemCoM/MJSystemCoM.cpp
  src/simulation/mujocoDynamics/MJSystemCoM/MJSystemCoM.rst
  src/simulation/mujocoDynamics/MJSystemCoM/_UnitTest/test_MJSystemCoM.py
Labels: documentation, refactor
